import { randomUUID } from 'node:crypto';
import pg from 'pg';
import { afterAll, describe, expect, it } from 'vitest';
import { config } from '../src/config.js';
import { contractPlanForTenant } from '../src/billing/contracts.js';
import { applyScheduledDowngrades, proratedAmountCents } from '../src/billing/proration.js';
const pool=new pg.Pool({connectionString:config.DATABASE_URL}); const tenants:string[]=[]; const plans:string[]=[];
async function q<T extends pg.QueryResultRow=pg.QueryResultRow>(s:string,v:unknown[]=[]){return (await pool.query<T>(s,v)).rows;}
async function fixture(){const n=`proration-${randomUUID()}`;const t=(await q<{id:string}>('INSERT INTO tenants(name,slug,status) VALUES($1,$1,\'active\') RETURNING id',[n]))[0].id;const a=(await q<{id:string}>('INSERT INTO plans(code,name,billing_period_months,monthly_price_cents) VALUES($1,$1,1,100) RETURNING id',[n+'-a']))[0].id;const b=(await q<{id:string}>('INSERT INTO plans(code,name,billing_period_months,monthly_price_cents) VALUES($1,$1,1,100) RETURNING id',[n+'-b']))[0].id;const c=(await q<{id:string}>('INSERT INTO plans(code,name,billing_period_months,monthly_price_cents) VALUES($1,$1,1,100) RETURNING id',[n+'-c']))[0].id;tenants.push(t);plans.push(a,b,c);await q("INSERT INTO plan_prices(plan_id,billing_cycle,base_price_cents,final_price_cents,currency) VALUES($1,'MONTHLY',10000,10000,'BRL'),($2,'MONTHLY',4000,4000,'BRL'),($3,'MONTHLY',14000,14000,'BRL')",[a,b,c]);await q("INSERT INTO tenant_subscriptions(tenant_id,plan_id,status,billing_cycle,base_price_cents,final_price_cents,current_period_start,current_period_end) VALUES($1,$2,'ACTIVE','MONTHLY',10000,10000,now()-interval '15 days',now()+interval '15 days')",[t,a]);return{t,a,b,c};}
afterAll(async()=>{if(tenants.length)await q('DELETE FROM tenants WHERE id=ANY($1::uuid[])',[tenants]);if(plans.length)await q('DELETE FROM plans WHERE id=ANY($1::uuid[])',[plans]);await pool.end()});
describe('proration and scheduled downgrades against Postgres',()=>{
 it('calculates remaining time proportionally and ends at zero',()=>{const s=new Date('2026-01-01T00:00:00Z'),e=new Date('2026-01-31T00:00:00Z');expect(proratedAmountCents(10000,s,e,new Date('2026-01-16T00:00:00Z'))).toBe(5000);expect(proratedAmountCents(10000,s,e,e)).toBe(0);});
 it('creates an upgrade proration invoice and PLAN line',async()=>{const x=await fixture();const s=await contractPlanForTenant(x.t,x.c,'MONTHLY','');expect(s.plan_id).toBe(x.c);const inv=await q<{amount_cents:string;id:string}>("SELECT id,amount_cents FROM invoices WHERE tenant_id=$1 AND kind='proration'",[x.t]);expect(inv).toHaveLength(1);expect(Number(inv[0].amount_cents)).toBe(2000);expect(Number((await q<{amount_cents:string}>("SELECT amount_cents FROM invoice_line_items WHERE invoice_id=$1 AND kind='PLAN'",[inv[0].id]))[0].amount_cents)).toBe(2000);});
 it('schedules downgrade without immediate swap, then applies only after cycle end',async()=>{const x=await fixture();const r=await contractPlanForTenant(x.t,x.b,'MONTHLY','');expect(r.plan_id).toBe(x.a);expect(r.scheduled_plan_id).toBe(x.b);expect((await q('SELECT plan_id,scheduled_plan_id FROM tenant_subscriptions WHERE tenant_id=$1',[x.t]))[0].plan_id).toBe(x.a);expect(await applyScheduledDowngrades()).toBe(0);await q("UPDATE tenant_subscriptions SET current_period_end=now()-interval '1 second' WHERE tenant_id=$1",[x.t]);expect(await applyScheduledDowngrades()).toBe(1);const s=(await q('SELECT plan_id,scheduled_plan_id FROM tenant_subscriptions WHERE tenant_id=$1',[x.t]))[0];expect(s.plan_id).toBe(x.b);expect(s.scheduled_plan_id).toBeNull();expect(Number((await q("SELECT count(*) n FROM subscription_events WHERE tenant_id=$1 AND event_type='SCHEDULED_DOWNGRADE_APPLIED'",[x.t]))[0].n)).toBe(1);});
});