import { randomUUID } from "node:crypto";
import pg from "pg";
import { afterAll, describe, expect, it } from "vitest";
import { config } from "../src/config.js";
import { redeemCoupon } from "../src/billing/coupons.js";
import { contractPlanForTenant } from "../src/billing/contracts.js";
import { createInvoiceForUsagePeriod } from "../src/billing/invoices.js";
const pool = new pg.Pool({ connectionString: config.DATABASE_URL }); const tenants:string[]=[]; const plans:string[]=[];
async function q<T extends pg.QueryResultRow=pg.QueryResultRow>(s:string,v:unknown[]=[]){return (await pool.query<T>(s,v)).rows;}
async function tenant(){const x=`coupon-${randomUUID()}`;const r=await q<{id:string}>("INSERT INTO tenants(name,slug,status) VALUES($1,$1,'active') RETURNING id",[x]);tenants.push(r[0].id);return r[0].id;}
async function make(code:string,opt:Record<string,unknown>={}){await q("INSERT INTO promotional_coupons(code,discount_type,discount_value,starts_at,expires_at,max_redemptions,redemption_count,eligibility) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT (code) DO UPDATE SET discount_type=EXCLUDED.discount_type,discount_value=EXCLUDED.discount_value,starts_at=EXCLUDED.starts_at,expires_at=EXCLUDED.expires_at,max_redemptions=EXCLUDED.max_redemptions,redemption_count=EXCLUDED.redemption_count,eligibility=EXCLUDED.eligibility",[code,opt.type??'FIXED',opt.value??1000,opt.starts??new Date(),opt.expires??null,opt.max??null,opt.count??0,opt.eligibility??{}]);}
async function redeem(code:string,t:string,plan='p'){const c=await pool.connect();try{await c.query('BEGIN');const r=await redeemCoupon(c,{code,tenantId:t,planId:plan,priceCents:10000});await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e}finally{c.release();}}
// Tenant com assinatura ACTIVE num plano com preço MONTHLY de R$100,00.
async function subscribed(){const t=await tenant();const plan=(await q<{id:string}>("INSERT INTO plans(code,name,billing_period_months,monthly_price_cents) VALUES($1,$1,1,10000) RETURNING id",[`coupon-plan-${randomUUID()}`]))[0].id;plans.push(plan);await q("INSERT INTO plan_prices(plan_id,billing_cycle,base_price_cents,final_price_cents,currency) VALUES($1,'MONTHLY',10000,10000,'BRL')",[plan]);await q("INSERT INTO tenant_subscriptions(tenant_id,plan_id,status,current_period_start,current_period_end) VALUES($1,$2,'ACTIVE',now()-interval '1 month',now()-interval '1 second')",[t,plan]);return {t,plan};}
afterAll(async()=>{if(tenants.length)await q("DELETE FROM tenants WHERE id=ANY($1::uuid[])",[tenants]);if(plans.length)await q("DELETE FROM plans WHERE id=ANY($1::uuid[])",[plans]);await pool.end();});
describe('promotional coupons against Postgres',()=>{
 it('applies percent and fixed discounts',async()=>{const t=await tenant();await make('P10',{type:'PERCENT',value:1000});await make('FIX',{value:2500});expect(Number((await redeem('P10',t)).discount_cents)).toBe(1000);expect(Number((await redeem('FIX',t)).discount_cents)).toBe(2500);});
 it('rejects expired, not-yet-valid, exhausted and ineligible coupons',async()=>{const t=await tenant();await make('EXP',{expires:new Date(Date.now()-1000)});await make('FUT',{starts:new Date(Date.now()+86400000)});await make('MAX',{max:1,count:1});await make('PLAN',{eligibility:{plan_ids:['other']}});for(const [code,err] of [['EXP','COUPON_EXPIRED'],['FUT','COUPON_EXPIRED'],['MAX','COUPON_EXHAUSTED'],['PLAN','COUPON_NOT_ELIGIBLE']])await expect(redeem(code,t)).rejects.toMatchObject({code:err});});
 it('is duplicate-idempotent and concurrent per tenant',async()=>{const t=await tenant();await make('ONCE');const a=await redeem('ONCE',t),b=await redeem('ONCE',t);expect(b.id).toBe(a.id);const t2=await tenant();const rs=await Promise.all([redeem('ONCE',t2),redeem('ONCE',t2)]);expect(new Set(rs.map(x=>x.id)).size).toBe(1);expect(Number((await q("SELECT redemption_count FROM promotional_coupons WHERE code='ONCE'"))[0].redemption_count)).toBe(2);expect(Number((await q("SELECT count(*) n FROM coupon_redemptions WHERE tenant_id=$1",[t2]))[0].n)).toBe(1);});
 it('C4: contracting with a coupon discounts the subscription snapshot and therefore the renewal invoice',async()=>{const x=await subscribed();const code=`C4-${randomUUID()}`;await make(code,{type:'PERCENT',value:1000});const s=await contractPlanForTenant(x.t,x.plan,'MONTHLY','',code);expect(Number(s.final_price_cents)).toBe(9000);expect(Number(s.base_price_cents)).toBe(10000);expect(Number((await q("SELECT discount_cents FROM coupon_redemptions WHERE tenant_id=$1",[x.t]))[0].discount_cents)).toBe(1000);
  await q("UPDATE tenant_subscriptions SET current_period_end=now()-interval '1 second' WHERE tenant_id=$1",[x.t]);await q("UPDATE usage_periods SET end_at=now()-interval '1 second',status='CLOSED' WHERE tenant_id=$1",[x.t]);const period=(await q<{id:string}>("SELECT id FROM usage_periods WHERE tenant_id=$1",[x.t]))[0].id;const invoice=await createInvoiceForUsagePeriod(pool,x.t,period);expect(invoice!.amount_cents).toBe("9000");});
 it('C4: a coupon never makes the price negative',async()=>{const x=await subscribed();const code=`C4F-${randomUUID()}`;await make(code,{type:'FIXED',value:50000});const s=await contractPlanForTenant(x.t,x.plan,'MONTHLY','',code);expect(Number(s.final_price_cents)).toBe(0);});
});
