import { randomUUID } from 'node:crypto';
import pg from 'pg';
import { afterAll, describe, expect, it } from 'vitest';
import { config } from '../src/config.js';
import { contractPlanForTenant } from '../src/billing/contracts.js';
import { applyScheduledDowngrades, proratedAmountCents } from '../src/billing/proration.js';
import { runBillingReconciliationBatch } from '../src/billing/reconciler.js';
const pool=new pg.Pool({connectionString:config.DATABASE_URL}); const tenants:string[]=[]; const plans:string[]=[];
async function q<T extends pg.QueryResultRow=pg.QueryResultRow>(s:string,v:unknown[]=[]){return (await pool.query<T>(s,v)).rows;}
async function fixture(){const n=`proration-${randomUUID()}`;const t=(await q<{id:string}>('INSERT INTO tenants(name,slug,status) VALUES($1,$1,\'active\') RETURNING id',[n]))[0].id;const a=(await q<{id:string}>('INSERT INTO plans(code,name,billing_period_months,monthly_price_cents) VALUES($1,$1,1,100) RETURNING id',[n+'-a']))[0].id;const b=(await q<{id:string}>('INSERT INTO plans(code,name,billing_period_months,monthly_price_cents) VALUES($1,$1,1,100) RETURNING id',[n+'-b']))[0].id;const c=(await q<{id:string}>('INSERT INTO plans(code,name,billing_period_months,monthly_price_cents) VALUES($1,$1,1,100) RETURNING id',[n+'-c']))[0].id;tenants.push(t);plans.push(a,b,c);await q("INSERT INTO plan_prices(plan_id,billing_cycle,base_price_cents,final_price_cents,currency) VALUES($1,'MONTHLY',10000,10000,'BRL'),($2,'MONTHLY',4000,4000,'BRL'),($3,'MONTHLY',14000,14000,'BRL'),($1,'YEARLY',120000,96000,'BRL')",[a,b,c]);await q("INSERT INTO tenant_subscriptions(tenant_id,plan_id,status,billing_cycle,base_price_cents,final_price_cents,current_period_start,current_period_end) VALUES($1,$2,'ACTIVE','MONTHLY',10000,10000,now()-interval '15 days',now()+interval '15 days')",[t,a]);await q("INSERT INTO usage_periods(tenant_id,subscription_id,sequence,start_at,end_at,included_limit,status) SELECT tenant_id,id,1,current_period_start,current_period_end,0,'OPEN' FROM tenant_subscriptions WHERE tenant_id=$1",[t]);return{t,a,b,c};}
// O tempo avança até o fim do ciclo contratado (e do período de uso alinhado a ele).
async function endCycle(t:string){await q("UPDATE tenant_subscriptions SET current_period_start=current_period_start-interval '1 month',current_period_end=now()-interval '1 second' WHERE tenant_id=$1",[t]);await q("UPDATE usage_periods SET start_at=start_at-interval '1 month',end_at=now()-interval '1 second' WHERE tenant_id=$1 AND status='OPEN'",[t]);}
async function planLines(t:string){return (await q<{amount_cents:string}>("SELECT l.amount_cents FROM invoice_line_items l JOIN invoices i ON i.id=l.invoice_id WHERE i.tenant_id=$1 AND i.kind='subscription' AND l.kind='PLAN' ORDER BY l.created_at",[t])).map(r=>Number(r.amount_cents));}
afterAll(async()=>{if(tenants.length)await q('DELETE FROM tenants WHERE id=ANY($1::uuid[])',[tenants]);if(plans.length)await q('DELETE FROM plans WHERE id=ANY($1::uuid[])',[plans]);await pool.end()});
describe('proration and scheduled downgrades against Postgres',()=>{
 it('calculates remaining time proportionally and ends at zero',()=>{const s=new Date('2026-01-01T00:00:00Z'),e=new Date('2026-01-31T00:00:00Z');expect(proratedAmountCents(10000,s,e,new Date('2026-01-16T00:00:00Z'))).toBe(5000);expect(proratedAmountCents(10000,s,e,e)).toBe(0);});
 it('creates an upgrade proration invoice and PLAN line',async()=>{const x=await fixture();const s=await contractPlanForTenant(x.t,x.c,'MONTHLY','');expect(s.plan_id).toBe(x.c);const inv=await q<{amount_cents:string;id:string}>("SELECT id,amount_cents FROM invoices WHERE tenant_id=$1 AND kind='proration'",[x.t]);expect(inv).toHaveLength(1);expect(Number(inv[0].amount_cents)).toBe(2000);expect(Number((await q<{amount_cents:string}>("SELECT amount_cents FROM invoice_line_items WHERE invoice_id=$1 AND kind='PLAN'",[inv[0].id]))[0].amount_cents)).toBe(2000);});
 // O downgrade agendado é aplicado NA virada do ciclo pelo caminho real de
 // faturamento (reconciliador), que antes cobra o ciclo que terminou pelo plano
 // antigo — o job isolado aplicava a troca antes e o PLAN do ciclo se perdia.
 it('schedules downgrade without immediate swap, then applies only after cycle end',async()=>{const x=await fixture();const r=await contractPlanForTenant(x.t,x.b,'MONTHLY','');expect(r.plan_id).toBe(x.a);expect(r.scheduled_plan_id).toBe(x.b);expect((await q('SELECT plan_id,scheduled_plan_id FROM tenant_subscriptions WHERE tenant_id=$1',[x.t]))[0].plan_id).toBe(x.a);expect(await applyScheduledDowngrades()).toBe(0);await runBillingReconciliationBatch(1000);expect((await q('SELECT plan_id FROM tenant_subscriptions WHERE tenant_id=$1',[x.t]))[0].plan_id).toBe(x.a);await endCycle(x.t);await runBillingReconciliationBatch(1000);const s=(await q('SELECT plan_id,scheduled_plan_id,final_price_cents,current_period_end > now() AS future FROM tenant_subscriptions WHERE tenant_id=$1',[x.t]))[0];expect(s.plan_id).toBe(x.b);expect(s.scheduled_plan_id).toBeNull();expect(Number(s.final_price_cents)).toBe(4000);expect(s.future).toBe(true);expect(await planLines(x.t)).toEqual([10000]);expect(Number((await q("SELECT count(*) n FROM subscription_events WHERE tenant_id=$1 AND event_type='SCHEDULED_DOWNGRADE_APPLIED'",[x.t]))[0].n)).toBe(1);});
 it('the standalone job still applies a due scheduled downgrade of a non-billed (SUSPENDED) subscription',async()=>{const x=await fixture();await contractPlanForTenant(x.t,x.b,'MONTHLY','');await q("UPDATE tenant_subscriptions SET status='SUSPENDED',current_period_end=now()-interval '1 second' WHERE tenant_id=$1",[x.t]);expect(await applyScheduledDowngrades(100000)).toBeGreaterThanOrEqual(1);expect((await q('SELECT plan_id FROM tenant_subscriptions WHERE tenant_id=$1',[x.t]))[0].plan_id).toBe(x.b);});
 it('C5: after the first cycle is billed by the reconciler, the contract cycle advances and a downgrade is still scheduled',async()=>{const x=await fixture();await endCycle(x.t);await runBillingReconciliationBatch(1000);expect(await planLines(x.t)).toEqual([10000]);const r=await contractPlanForTenant(x.t,x.b,'MONTHLY','');expect(r.plan_id).toBe(x.a);expect(r.scheduled_plan_id).toBe(x.b);});
 it('C5: an upgrade in cycle 2 still creates a proration invoice',async()=>{const x=await fixture();await endCycle(x.t);await runBillingReconciliationBatch(1000);await contractPlanForTenant(x.t,x.c,'MONTHLY','');expect((await q("SELECT 1 FROM invoices WHERE tenant_id=$1 AND kind='proration'",[x.t])).length).toBe(1);});
 it('S7: switching MONTHLY to YEARLY mid-cycle settles only the elapsed monthly fraction and restarts a yearly cycle (no cross-cycle proration)',async()=>{const x=await fixture();await contractPlanForTenant(x.t,x.a,'YEARLY','');const inv=await q<{amount_cents:string}>("SELECT amount_cents FROM invoices WHERE tenant_id=$1 AND kind='proration'",[x.t]);expect(inv).toHaveLength(1);expect(Number(inv[0].amount_cents)).toBeGreaterThan(4800);expect(Number(inv[0].amount_cents)).toBeLessThan(5200);const s=(await q("SELECT billing_cycle,current_period_end > now()+interval '11 months' AS yearly FROM tenant_subscriptions WHERE tenant_id=$1",[x.t]))[0];expect(s.billing_cycle).toBe('YEARLY');expect(s.yearly).toBe(true);});
 it('C6: switching YEARLY to MONTHLY in month 11 invoices the elapsed annual fee instead of dropping it',async()=>{const x=await fixture();await q("UPDATE tenant_subscriptions SET billing_cycle='YEARLY',base_price_cents=120000,final_price_cents=96000,current_period_start=now()-interval '11 months',current_period_end=now()+interval '1 month' WHERE tenant_id=$1",[x.t]);await contractPlanForTenant(x.t,x.a,'MONTHLY','');const total=Number((await q<{n:string}>("SELECT COALESCE(sum(amount_cents),0) n FROM invoices WHERE tenant_id=$1",[x.t]))[0].n);expect(total).toBeGreaterThan(85000);expect(total).toBeLessThan(90000);});
});