import { randomUUID } from "node:crypto";
import pg from "pg";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { config } from "../src/config.js";
import { contractPlanForTenant, upsertPlanPrice } from "../src/billing/contracts.js";

const pool = new pg.Pool({ connectionString: config.DATABASE_URL });
const tenants: string[] = [], plans: string[] = [];
const cycles = ["MONTHLY", "QUARTERLY", "YEARLY"] as const;
const seed = { BASIC: [49700, 49700, 0], MEDIUM: [89700, 89700, 0], PRO: [109700, 109700, 0] } as const;
async function q<T extends pg.QueryResultRow = pg.QueryResultRow>(sql: string, values: unknown[] = []) { return (await pool.query<T>(sql, values)).rows; }
async function fixture() {
  const slug = `r11-contract-${randomUUID()}`;
  const tenant = (await q<{ id: string}>("INSERT INTO tenants(name,slug,status) VALUES($1,$1,'active') RETURNING id", [slug]))[0].id; tenants.push(tenant);
  const plan = (await q<{ id: string}>("INSERT INTO plans(code,name,billing_period_months,monthly_price_cents) VALUES($1,$1,1,100) RETURNING id", [slug]))[0].id; plans.push(plan);
  await q("INSERT INTO tenant_subscriptions(tenant_id,plan_id,status,current_period_start,current_period_end) VALUES($1,$2,'ACTIVE',now(),now()+interval '1 month')", [tenant, plan]);
  return { tenant, plan };
}
beforeAll(async () => { for (const [code, [monthly, ,]] of Object.entries(seed)) { const rows = await q<{id:string}>("SELECT id FROM plans WHERE code=$1", [code]); if (!rows[0]) throw new Error(`missing seeded plan ${code}`); for (const [cycle, base, discount] of [["MONTHLY", monthly, 0], ["QUARTERLY", monthly * 3, 1000], ["YEARLY", monthly * 12, 2000]] as const) { const c = await pool.connect(); try { await c.query("BEGIN"); await upsertPlanPrice(c, { planId: rows[0].id, billingCycle: cycle, basePriceCents: base, discountType: discount ? "PERCENT" : null, discountValue: discount, currency: "BRL" }, "r11"); await c.query("COMMIT"); } finally { c.release(); } } } });
afterAll(async () => { if (tenants.length) await q("DELETE FROM tenants WHERE id=ANY($1::uuid[])", [tenants]); if (plans.length) await q("DELETE FROM plans WHERE id=ANY($1::uuid[])", [plans]); await pool.end(); });

describe("R11 billing contracts", () => {
  it("has exact BASIC/MEDIUM/PRO monthly, quarterly and yearly seeds", async () => { for (const [code, [monthly]] of Object.entries(seed)) { const p = (await q<pg.QueryResultRow>("SELECT id FROM plans WHERE code=$1", [code]))[0]; const rows = await q<pg.QueryResultRow>("SELECT billing_cycle,base_price_cents,discount_type,discount_value,final_price_cents,currency FROM plan_prices WHERE plan_id=$1 AND active ORDER BY billing_cycle", [p.id]); expect(rows).toHaveLength(3); expect(rows.map(x => [x.billing_cycle, Number(x.base_price_cents), x.discount_type, Number(x.discount_value ?? 0), Number(x.final_price_cents), x.currency])).toEqual([["MONTHLY", monthly, null, 0, monthly, "BRL"],["QUARTERLY", monthly*3,"PERCENT",1000,Math.floor(monthly*3*0.9),"BRL"],["YEARLY",monthly*12,"PERCENT",2000,Math.floor(monthly*12*0.8),"BRL"]]); } });
  it.each(cycles)("snapshots %s price and uses one calendar-month usage period", async (cycle) => { const x = await fixture(); const c = await pool.connect(); try { await c.query("BEGIN"); await upsertPlanPrice(c, {planId:x.plan,billingCycle:cycle,basePriceCents:12000,discountType:"FIXED",discountValue:cycle === "MONTHLY" ? 100 : 1000,currency:"USD"}, "r11"); await c.query("COMMIT"); } finally { c.release(); } const s: pg.QueryResultRow = await contractPlanForTenant(x.tenant,x.plan,cycle,""); expect([Number(s.base_price_cents),Number(s.final_price_cents),s.snapshot_currency,s.billing_cycle]).toEqual([12000,cycle === "MONTHLY" ? 11900 : 11000,"USD",cycle]); expect(Number((await q<pg.QueryResultRow>("SELECT EXTRACT(epoch FROM (end_at-start_at))/86400 AS d FROM usage_periods WHERE tenant_id=$1",[x.tenant]))[0].d)).toBeGreaterThan(27); expect(Number((await q<pg.QueryResultRow>("SELECT EXTRACT(month FROM age(end_at,start_at)) AS m FROM usage_periods WHERE tenant_id=$1",[x.tenant]))[0].m)).toBe(1); });
  it("versioning deactivates old, snapshots new, and concurrency emits one coherent event", async () => { const x=await fixture(); const c=await pool.connect(); try { await c.query("BEGIN"); const old=await upsertPlanPrice(c,{planId:x.plan,billingCycle:"MONTHLY",basePriceCents:1000,currency:"BRL"},"r11"); const newer=await upsertPlanPrice(c,{planId:x.plan,billingCycle:"MONTHLY",basePriceCents:2000,currency:"BRL"},"r11"); await c.query("COMMIT"); const a=contractPlanForTenant(x.tenant,x.plan,"MONTHLY",""); const b=contractPlanForTenant(x.tenant,x.plan,"MONTHLY",""); await expect(Promise.all([a,b])).resolves.toHaveLength(2); expect((await q<pg.QueryResultRow>("SELECT count(*)::int n FROM subscription_events WHERE tenant_id=$1",[x.tenant]))[0].n).toBe(2); expect((await q<pg.QueryResultRow>("SELECT count(*)::int n FROM plan_prices WHERE id=$1 AND active=false",[String(old.id)]))[0].n).toBe(1); expect((await q<pg.QueryResultRow>("SELECT count(*)::int n FROM plan_prices WHERE id=$1 AND active=true",[String(newer.id)]))[0].n).toBe(1); } finally { c.release(); } });
  it("rejects invalid discounts/finals without changing active version", async () => { const x=await fixture(); const c=await pool.connect(); try { await c.query("BEGIN"); await expect(Promise.resolve().then(()=>upsertPlanPrice(c,{planId:x.plan,billingCycle:"MONTHLY",basePriceCents:100,discountType:"PERCENT",discountValue:10001,currency:"BRL"},"r11"))).rejects.toThrow(); await c.query("ROLLBACK"); } finally { c.release(); } expect((await q<pg.QueryResultRow>("SELECT count(*)::int n FROM plan_prices WHERE plan_id=$1 AND billing_cycle='MONTHLY'",[x.plan]))[0].n).toBe(0); });
});
