import { randomUUID } from "node:crypto";
import pg from "pg";
import { afterAll, describe, expect, it } from "vitest";
import { config } from "../src/config.js";
import { ensureOpenPeriod } from "../src/billing/usage-period.js";
import { closePeriodAndGrantRollover, expireRollover, previewRollover, truncateRolloverToPlanCap } from "../src/billing/rollover.js";

const pool = new pg.Pool({ connectionString: config.DATABASE_URL });
const tenants: string[] = [], plans: string[] = [];
async function setup(opts: { limit?: number; rate?: number; cap?: number; status?: string } = {}) {
  const slug = `rollover-${randomUUID()}`;
  const t = (await pool.query<{id:string}>("INSERT INTO tenants(name,slug,status) VALUES($1,$1,'active') RETURNING id", [slug])).rows[0].id; tenants.push(t);
  const code = `ROLL_${randomUUID()}`;
  const p = (await pool.query<{id:string}>(`INSERT INTO plans(code,name,billing_period_months,monthly_price_cents,rollover_enabled,rollover_rate_bps,rollover_max_percentage_bps,rollover_expiration_periods) VALUES($1,$1,1,0,true,$2,$3,1) RETURNING id`, [code, opts.rate ?? 5000, opts.cap ?? 5000])).rows[0].id; plans.push(p);
  await pool.query("INSERT INTO plan_limits(plan_id,limit_key,limit_value) VALUES($1,'MAX_AI_INTERACTIONS',$2)", [p, opts.limit ?? 10000]);
  await pool.query("INSERT INTO tenant_subscriptions(tenant_id,plan_id,status,current_period_start,current_period_end) VALUES($1,$2,$3,now(),now()+interval '1 month')", [t,p,opts.status ?? "ACTIVE"]);
  const c = await pool.connect(); let source: Awaited<ReturnType<typeof ensureOpenPeriod>>;
  try { await c.query("BEGIN"); await c.query("SELECT id FROM tenant_subscriptions WHERE tenant_id=$1 FOR UPDATE", [t]); source = await ensureOpenPeriod(c,t); if (!source) throw new Error("expected source period"); await c.query("UPDATE usage_periods SET status='CLOSED',included_usage=0 WHERE id=$1",[source.id]); await c.query("UPDATE usage_periods SET sequence=2 WHERE id=$1", [source.id]); const target=(await c.query("INSERT INTO usage_periods(tenant_id,subscription_id,sequence,start_at,end_at,included_limit,status) SELECT tenant_id,subscription_id,sequence+1,end_at,end_at+interval '1 month',included_limit,'OPEN' FROM usage_periods WHERE id=$1 RETURNING id",[source.id])).rows[0]; await c.query("COMMIT"); return {t,source:source.id,target:target.id}; } catch(e) { await c.query("ROLLBACK"); throw e; } finally { c.release(); }
}
async function tx<T>(fn:(c:pg.PoolClient)=>Promise<T>) { const c=await pool.connect(); try { await c.query("BEGIN"); const x=await fn(c); await c.query("COMMIT"); return x; } catch(e) { await c.query("ROLLBACK"); throw e; } finally { c.release(); } }
async function val(sql:string,p:unknown[]=[]){return (await pool.query(sql,p)).rows[0];}
async function grant(t:string,target:string,amount:number,expired=false){await pool.query("INSERT INTO rollover_ledger(tenant_id,usage_period_id,generated_amount,consumed_amount,expired_amount,rollover_rate_bps,expires_at) VALUES($1,$2,$3,0,0,5000,$4)",[t,target,amount,expired?"2000-01-01":"2099-01-01"]);}
afterAll(async()=>{if(tenants.length)await pool.query("DELETE FROM tenants WHERE id=ANY($1::uuid[])",[tenants]);if(plans.length)await pool.query("DELETE FROM plans WHERE id=ANY($1::uuid[])",[plans]);await pool.end();});

describe("billing rollover against Postgres",()=>{
 it("a) franquia toda gera zero",async()=>{const x=await setup();await pool.query("UPDATE usage_periods SET included_usage=included_limit WHERE id=$1",[x.source]);expect((await tx(c=>closePeriodAndGrantRollover(c,x.t,x.source,x.target))).generated).toBe(0);expect((await val("SELECT rollover_granted FROM usage_periods WHERE id=$1",[x.target])).rollover_granted).toBe("0");});
 it("b) metade gera 2500",async()=>{const x=await setup();await pool.query("UPDATE usage_periods SET included_usage=5000 WHERE id=$1",[x.source]);await tx(c=>closePeriodAndGrantRollover(c,x.t,x.source,x.target));expect((await val("SELECT rollover_granted FROM usage_periods WHERE id=$1",[x.target])).rollover_granted).toBe("2500");});
 it("c) zero e limitado ao cap de 50 por cento",async()=>{const x=await setup({rate:10000,cap:5000});await tx(c=>closePeriodAndGrantRollover(c,x.t,x.source,x.target));expect((await val("SELECT rollover_granted FROM usage_periods WHERE id=$1",[x.target])).rollover_granted).toBe("5000");});
 it("d) expira e deixa saldo indisponivel",async()=>{const x=await setup();await grant(x.t,x.target,2500,true);expect(await tx(c=>expireRollover(c,x.t))).toBe(2500);expect((await tx(c=>previewRollover(c,x.t))).currentBalance).toBe(0);expect((await val("SELECT expired_amount FROM rollover_ledger WHERE tenant_id=$1",[x.t])).expired_amount).toBe("2500");});
 it("e) nao gera rollover sobre rollover",async()=>{const x=await setup();await grant(x.t,x.source,2500);await pool.query("UPDATE usage_periods SET included_usage=0,rollover_granted=2500 WHERE id=$1",[x.source]);await tx(c=>closePeriodAndGrantRollover(c,x.t,x.source,x.target));expect((await val("SELECT rollover_granted FROM usage_periods WHERE id=$1",[x.target])).rollover_granted).toBe("5000");});
 it("f) overage nao gera rollover",async()=>{const x=await setup();await pool.query("UPDATE usage_periods SET included_usage=included_limit,overage_usage=9000 WHERE id=$1",[x.source]);expect((await tx(c=>closePeriodAndGrantRollover(c,x.t,x.source,x.target))).generated).toBe(0);});
 it("g) bonus nao entra na base",async()=>{const x=await setup();await pool.query("UPDATE usage_periods SET bonus_granted=90000,bonus_usage=0,included_usage=5000 WHERE id=$1",[x.source]);await tx(c=>closePeriodAndGrantRollover(c,x.t,x.source,x.target));expect((await val("SELECT rollover_granted FROM usage_periods WHERE id=$1",[x.target])).rollover_granted).toBe("2500");});
 it("h) status invalido nao gera e informa razao",async()=>{for(const status of ["PAST_DUE","SUSPENDED","CANCELED"]){const x=await setup({status});const r=await tx(c=>closePeriodAndGrantRollover(c,x.t,x.source,x.target));expect(r).toMatchObject({generated:0,reason:"INVALID_SUBSCRIPTION_STATUS"});expect((await val("SELECT rollover_granted FROM usage_periods WHERE id=$1",[x.target])).rollover_granted).toBe("0");}});
 it("i) fechamento duas vezes e idempotente",async()=>{const x=await setup();const a=await tx(c=>closePeriodAndGrantRollover(c,x.t,x.source,x.target));const b=await tx(c=>closePeriodAndGrantRollover(c,x.t,x.source,x.target));expect(a.generated).toBe(5000);expect(b.generated).toBe(0);expect((await val("SELECT rollover_granted FROM usage_periods WHERE id=$1",[x.target])).rollover_granted).toBe("5000");expect((await val("SELECT count(*)::int AS n FROM rollover_ledger WHERE tenant_id=$1",[x.t])).n).toBe(1);});
 it("j) webhook repetido respeita unique",async()=>{const x=await setup();await tx(c=>closePeriodAndGrantRollover(c,x.t,x.source,x.target));await tx(c=>closePeriodAndGrantRollover(c,x.t,x.source,x.target));expect((await val("SELECT count(*)::int AS n FROM rollover_ledger WHERE tenant_id=$1",[x.t])).n).toBe(1);});
 it("k) concorrencia concede uma vez",async()=>{const x=await setup();const [a,b]=await Promise.all([tx(c=>closePeriodAndGrantRollover(c,x.t,x.source,x.target)),tx(c=>closePeriodAndGrantRollover(c,x.t,x.source,x.target))]);expect([a.generated,b.generated].sort()).toEqual([0,5000]);expect((await val("SELECT rollover_granted FROM usage_periods WHERE id=$1",[x.target])).rollover_granted).toBe("5000");expect((await val("SELECT count(*)::int AS n FROM rollover_ledger WHERE tenant_id=$1",[x.t])).n).toBe(1);});
 it("l) truncamento registra remocao e evento",async()=>{const x=await setup();await grant(x.t,x.target,5000);const np=(await pool.query<{id:string}>("INSERT INTO plans(code,name,billing_period_months,monthly_price_cents,rollover_enabled,rollover_rate_bps,rollover_max_percentage_bps) VALUES($1,$1,1,0,true,5000,2000) RETURNING id",[`NEW_${randomUUID()}`])).rows[0].id;plans.push(np);await pool.query("INSERT INTO plan_limits(plan_id,limit_key,limit_value) VALUES($1,'MAX_AI_INTERACTIONS',10000)",[np]);const r=await tx(c=>truncateRolloverToPlanCap(c,x.t,np));expect(r.removed).toBe(3000);expect((await val("SELECT expired_amount FROM rollover_ledger WHERE tenant_id=$1",[x.t])).expired_amount).toBe("3000");expect((await val("SELECT count(*)::int AS n FROM subscription_events WHERE tenant_id=$1 AND event_type='ROLLOVER_ADJUSTED_BY_ROOT'",[x.t])).n).toBe(1);});
 it("m) ledger audita origem e calculo",async()=>{const x=await setup();await pool.query("UPDATE usage_periods SET included_usage=5000 WHERE id=$1",[x.source]);await tx(c=>closePeriodAndGrantRollover(c,x.t,x.source,x.target));const r=await val("SELECT source_period_id,rollover_rate_bps,generated_amount,unused_included_usage FROM rollover_ledger WHERE tenant_id=$1",[x.t]);expect(r.source_period_id).toBe(x.source);expect(r.rollover_rate_bps).toBe(5000);expect(r.generated_amount).toBe("2500");expect(r.unused_included_usage).toBe("5000");});
});
