import { randomUUID } from "node:crypto";
import pg from "pg";
import { afterAll, describe, expect, it } from "vitest";
import { config } from "../src/config.js";
import { contractPlanForTenant } from "../src/billing/contracts.js";
import { changeStatus } from "../src/modules/saas/service.js";

const pool = new pg.Pool({ connectionString: config.DATABASE_URL });
const tenants:string[]=[], plans:string[]=[], users:string[]=[];
async function plan(code:string, cap:number) { const id=(await pool.query<{id:string}>("INSERT INTO plans(code,name,billing_period_months,monthly_price_cents,rollover_enabled,rollover_rate_bps,rollover_max_percentage_bps) VALUES($1,$1,1,0,true,10000,$2) RETURNING id",[code,cap])).rows[0].id; plans.push(id); await pool.query("INSERT INTO plan_limits(plan_id,limit_key,limit_value) VALUES($1,'MAX_AI_INTERACTIONS',100)",[id]); await pool.query("INSERT INTO plan_prices(plan_id,billing_cycle,base_price_cents,final_price_cents,currency,active) VALUES($1,'MONTHLY',0,0,'BRL',true)",[id]); return id; }
async function fixture(status="ACTIVE", end="2099-01-01") { const slug=`plan-change-${randomUUID()}`; const tenant=(await pool.query<{id:string}>("INSERT INTO tenants(name,slug,status) VALUES($1,$1,'active') RETURNING id",[slug])).rows[0].id; tenants.push(tenant); const old=await plan(`OLD_${randomUUID()}`,10000), next=await plan(`NEW_${randomUUID()}`,2000); await pool.query("UPDATE plan_limits SET limit_value=10000 WHERE plan_id=$1",[next]); const sub=(await pool.query<{id:string}>("INSERT INTO tenant_subscriptions(tenant_id,plan_id,status,current_period_start,current_period_end) VALUES($1,$2,$3,now()-interval '10 days',$4) RETURNING id",[tenant,old,status,end])).rows[0].id; await pool.query("INSERT INTO usage_periods(tenant_id,subscription_id,sequence,start_at,end_at,included_limit,status) VALUES($1,$2,1,now()-interval '10 days',now()+interval '20 days',100,'OPEN')",[tenant,sub]); const actor=(await pool.query<{id:string}>("INSERT INTO users(email,status) VALUES($1,'active') RETURNING id",[`plan-change-${randomUUID()}@test.local`])).rows[0].id; users.push(actor); return {tenant,old,next,sub,actor}; }
async function scalar<T=unknown>(sql:string,args:unknown[]=[]) { return (await pool.query<{value:T}>(sql,args)).rows[0]?.value; }
async function rollover(t:string, amount:number) { await pool.query("INSERT INTO rollover_ledger(tenant_id,usage_period_id,generated_amount,consumed_amount,expired_amount,rollover_rate_bps,expires_at) VALUES($1,(SELECT id FROM usage_periods WHERE tenant_id=$1 LIMIT 1),$2,0,0,10000,'2099-01-01')",[t,amount]); }
afterAll(async()=>{if(tenants.length)await pool.query("DELETE FROM tenants WHERE id=ANY($1::uuid[])",[tenants]);if(plans.length)await pool.query("DELETE FROM plans WHERE id=ANY($1::uuid[])",[plans]);if(users.length)await pool.query("UPDATE audit_logs SET actor_user_id=NULL WHERE actor_user_id=ANY($1::uuid[])",[users]);if(users.length)await pool.query("DELETE FROM users WHERE id=ANY($1::uuid[])",[users]);await pool.end();});

describe("commercial plan lifecycle integration",()=>{
  it("preserves a live paid cycle and records preserved",async()=>{const x=await fixture();const before=await scalar<string>("SELECT current_period_end::text AS value FROM tenant_subscriptions WHERE id=$1",[x.sub]);await contractPlanForTenant(x.tenant,x.next,"MONTHLY","");expect(await scalar<string>("SELECT current_period_end::text AS value FROM tenant_subscriptions WHERE id=$1",[x.sub])).toBe(before);expect(await scalar("SELECT metadata->>'cycle' AS value FROM subscription_events WHERE subscription_id=$1",[x.sub])).toBe("preserved");});
  it("restarts an expired cycle and keeps CANCELED non-active",async()=>{const x=await fixture("CANCELED","2000-01-01");await contractPlanForTenant(x.tenant,x.next,"MONTHLY","");expect(await scalar("SELECT status AS value FROM tenant_subscriptions WHERE id=$1",[x.sub])).toBe("CANCELED");expect(await scalar("SELECT metadata->>'cycle' AS value FROM subscription_events WHERE subscription_id=$1",[x.sub])).toBe("restarted");expect(await scalar("SELECT current_period_end > now() AS value FROM tenant_subscriptions WHERE id=$1",[x.sub])).toBe(true);});
  it("truncates rollover on a real downgrade, but not when plan is unchanged",async()=>{const x=await fixture();await rollover(x.tenant,5000);await contractPlanForTenant(x.tenant,x.next,"MONTHLY","");expect(await scalar("SELECT expired_amount AS value FROM rollover_ledger WHERE tenant_id=$1",[x.tenant])).toBe("3000");expect(await scalar("SELECT count(*)::int AS value FROM subscription_events WHERE tenant_id=$1 AND event_type='ROLLOVER_ADJUSTED_BY_ROOT'",[x.tenant])).toBe(1);const same=await fixture();await rollover(same.tenant,5000);await contractPlanForTenant(same.tenant,same.old,"MONTHLY","");expect(await scalar("SELECT expired_amount AS value FROM rollover_ledger WHERE tenant_id=$1",[same.tenant])).toBe("0");});
  it("reactivates expired CANCELED with a valid period and clears grace",async()=>{const x=await fixture("CANCELED","2000-01-01");await pool.query("UPDATE tenant_subscriptions SET grace_period_ends_at=now()+interval '2 days' WHERE id=$1",[x.sub]);await changeStatus(x.tenant,"ACTIVE",x.actor);expect(await scalar("SELECT current_period_end > now() AS value FROM tenant_subscriptions WHERE id=$1",[x.sub])).toBe(true);expect(await scalar("SELECT grace_period_ends_at IS NULL AS value FROM tenant_subscriptions WHERE id=$1",[x.sub])).toBe(true);});
  it("does not change a still-valid period on reactivation",async()=>{const x=await fixture("CANCELED","2099-01-01");const before=await scalar<string>("SELECT current_period_end::text AS value FROM tenant_subscriptions WHERE id=$1",[x.sub]);await changeStatus(x.tenant,"ACTIVE",x.actor);expect(await scalar<string>("SELECT current_period_end::text AS value FROM tenant_subscriptions WHERE id=$1",[x.sub])).toBe(before);});
});
