import { api } from "./api";

export type ConversationDeltaResponse = Record<string, unknown>;
export type ConversationAssetsResponse = Record<string, unknown>;
const action = (path: string, method: string, body?: unknown) => api<unknown>(path, { method, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
export const fetchConversations = <T = ConversationDeltaResponse>(path = "/conversations") => api<T>(path);
export const markConversationRead = (id: string) => action(`/conversations/${id}/read`, "PATCH");
export const reactivateConversation = (id: string) => action(`/conversations/${id}/reactivate`, "PATCH");
export const requestConversationAiReply = (id: string) => action(`/conversations/${id}/reply-with-ai`, "POST");
export const pauseConversation = (id: string) => action(`/conversations/${id}/pause`, "PATCH");
export const claimConversation = (id: string) => action(`/conversations/${id}/claim`, "PATCH");
export const followUpConversation = (id: string, body: unknown) => action(`/conversations/${id}/follow-up`, "POST", body);
export const resolveConversation = (id: string) => action(`/conversations/${id}/resolve`, "PATCH");
export const reopenConversation = (id: string) => action(`/conversations/${id}/reopen`, "PATCH");
export const reactToMessage = (conversationId: string, messageId: string, emoji: string | null) => action(`/conversations/${conversationId}/messages/${messageId}/react`, "POST", { emoji: emoji || null });
export const editMessage = (conversationId: string, messageId: string, text: string) => action(`/conversations/${conversationId}/messages/${messageId}`, "PATCH", { text });
export const deleteMessage = (conversationId: string, messageId: string, forEveryone: boolean) => action(`/conversations/${conversationId}/messages/${messageId}`, "DELETE", { forEveryone });
export const assignConversation = (id: string, userId: string | null) => action(`/conversations/${id}/assign`, "PATCH", { userId: userId || null });
export const setConversationSignature = (id: string, enabled: boolean | null) => action(`/conversations/${id}/signature`, "PATCH", { enabled });
export const setConversationNotificationMute = (id: string, muted: boolean) => action(`/conversations/${id}/notification-mute`, "PATCH", { muted });
export const runConversationEvaluation = (conversationId: string) => action("/agent/evaluations/run", "POST", { conversationId });
export const deleteConversationMessages = (id: string) => action(`/conversations/${id}/messages`, "DELETE");
export const renameConversationContact = (id: string, name: string) => action(`/conversations/${id}/contact`, "PATCH", { name });
export const fetchConversationAssets = <T = ConversationAssetsResponse>(id: string, query = "limit=50", signal?: AbortSignal) => api<T>(`/conversations/${id}/assets?${query}`, { signal });
