"use client";

import { useEffect, useState } from "react";
import useSWR from "swr";
import { Shell } from "@/components/shell";
import { api } from "@/lib/api";
import type { PanelSession } from "@/lib/session";

type Gateway = { code: string; name: string; environment: "sandbox" | "production"; status: string; credentials_hint?: string | null; commercial_config?: Record<string, string | number | boolean> };
const fetcher = <T,>(url: string) => api<T>(url);
const providers = ["Mercado Pago", "Stripe", "InfinitePay", "PagBank"];
// O backend identifica o provedor pelo CODE, nunca pelo nome de exibição:
// montar a URL com o rótulo geraria um path com espaço ("/Stripe/...").
const PROVIDER_CODES: Record<string, string> = { "Mercado Pago": "mercadopago", "PIX Manual": "manual_pix" };
export default function GatewaysPage() {
  const { data: session } = useSWR<PanelSession>("/me", fetcher, { revalidateOnFocus: false });
  const root = Boolean(session?.user.isRoot);
  const { data, mutate } = useSWR<{ providers: Gateway[] }>(root ? "/root/billing/providers" : null, fetcher);
  const [form, setForm] = useState<{ provider: string; environment: Gateway["environment"] } | null>(null);
  const [message, setMessage] = useState("");
  useEffect(() => { const result = new URLSearchParams(window.location.search).get("mercadopago"); if (!result) return; setMessage(result === "connected" ? "Mercado Pago conectado via OAuth." : "Não foi possível concluir a conexão OAuth do Mercado Pago. Verifique as credenciais da aplicação e tente novamente."); window.history.replaceState({}, "", window.location.pathname); }, []);
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!form) return; const values = Object.fromEntries(new FormData(event.currentTarget)); const clientSecret = String(values.clientSecret ?? ""); try { await api(`/root/billing/providers/${PROVIDER_CODES[form.provider] ?? form.provider}/${form.environment}/credentials`, { method: "PUT", body: JSON.stringify({ credentials: { clientId: values.clientId, clientSecret, ...(values.redirectUri ? { redirectUri: values.redirectUri } : {}) } }) }); setForm(null); setMessage("Credenciais salvas. O segredo não é exibido novamente."); await mutate(); } catch (e) { setMessage(e instanceof Error ? e.message : "Não foi possível salvar."); } }
  async function disconnect(g: Gateway) { if (!window.confirm(`Desconectar ${g.name} (${g.environment})? Isso remove apenas as credenciais locais do AtendON. O Mercado Pago não oferece API para revogação remota; para revogar totalmente o acesso, faça isso manualmente na sua conta do Mercado Pago em Configurações > Suas integrações.`)) return; await api(`/root/billing/providers/${g.code}/${g.environment}/disconnect`, { method: "POST", body: JSON.stringify({ confirm: true }) }); setMessage("Gateway desconectado localmente. O Mercado Pago não oferece API para revogação remota. Para revogar totalmente o acesso, faça isso manualmente na sua conta do Mercado Pago em Configurações > Suas integrações."); await mutate(); }
  async function connectOAuth(environment: Gateway["environment"]) { try { const result = await api<{ authorizationUrl: string }>(`/root/billing/providers/${environment}/oauth/begin`, { method: "POST", body: JSON.stringify({ redirectUri: `${window.location.origin}/billing/providers/mercadopago/oauth/callback` }) }); window.location.assign(result.authorizationUrl); } catch (e) { setMessage(e instanceof Error ? e.message : "Não foi possível iniciar o OAuth."); } }
  async function testConnection(environment: Gateway["environment"]) { try { await api(`/root/billing/providers/${environment}/test-connection`, { method: "POST" }); setMessage("Conexão validada."); await mutate(); } catch (e) { setMessage(e instanceof Error ? e.message : "Não foi possível testar a conexão."); } }
  if (!root) return <Shell><div className="card"><p>Esta área está disponível apenas para usuários ROOT.</p></div></Shell>;
  return <Shell><header className="pagehead"><div><h1>Gateways</h1><p>Credenciais e configurações por provedor e ambiente.</p></div></header>{message && <p className="accent" role="status">{message}</p>}<section className="grid gap-4 sm:grid-cols-2">{providers.flatMap((provider) => (["sandbox", "production"] as const).map((environment) => { const g = data?.providers?.find((x) => x.name === provider && x.environment === environment); const active = provider === "Mercado Pago"; return <article className={`card ${environment === "sandbox" ? "border-dashed" : ""}`} key={`${provider}-${environment}`}><div className="flex items-center justify-between"><h2>{provider}</h2><span className="sub">{environment === "sandbox" ? "Sandbox" : "Produção"}</span></div><p className="mt-2">{active ? (g?.status ?? "Não conectado") : "Em breve"}</p>{g?.credentials_hint && <p className="sub">Conta: {g.credentials_hint}</p>}<div className="admin-actions mt-3"><button className="btn primary" type="button" disabled={!active} onClick={() => setForm({ provider, environment })}>{active ? "Conectar / credenciais" : "Indisponível"}</button><button className="btn" type="button" disabled={!active || !g} onClick={() => void testConnection(environment)}>Testar conexão</button><button className="btn" type="button" disabled={!active} onClick={() => void connectOAuth(environment)}>Conectar via OAuth</button><button className="btn warn" type="button" disabled={!g} onClick={() => g && void disconnect(g)}>Desconectar</button></div><p className="sub mt-2">OAuth e teste de conexão disponíveis para Mercado Pago.</p></article>; }))}</section>{form && <div className="card mt-4"><h2>Credenciais · {form.provider} · {form.environment}</h2><p className="sub">Segredos são enviados apenas no salvamento e nunca repopulados. Use o Client ID e o Client Secret da sua aplicação em Mercado Pago &gt; Suas integrações.</p><form className="mt-3" onSubmit={save}><label className="field"><span className="label">Client ID</span><input className="input" name="clientId" autoComplete="off" required /></label><label className="field"><span className="label">Client Secret</span><input className="input" name="clientSecret" type="password" autoComplete="new-password" required /></label><label className="field"><span className="label">Redirect URI (opcional)</span><input className="input" name="redirectUri" autoComplete="off" placeholder={`${typeof window === "undefined" ? "" : window.location.origin}/billing/providers/mercadopago/oauth/callback`} /></label><div className="admin-actions mt-3"><button className="btn primary" type="submit">Salvar</button><button className="btn" type="button" onClick={() => setForm(null)}>Cancelar</button></div></form></div>}</Shell>;
}
