"use client";

import { useState, type FormEvent } from "react";
import useSWR from "swr";
import { Shell } from "@/components/shell";
import { Empty } from "@/components/page-state";
import { ModalDialog } from "@/components/modal-dialog";
import { api } from "@/lib/api";
import type { PanelSession } from "@/lib/session";
import { duplicatePlanPayload, formatUsage, normalizePlan, reaisToCents, type Catalog, type Plan } from "@/lib/saas-plans";

type Usage = { MAX_USERS: number; MAX_WHATSAPP_CONNECTIONS: number; MAX_AI_INTERACTIONS: number };
type Tenant = { id: string; name: string; status: string; subscription_status: string | null; plan_code: string | null; plan_name: string | null; entitlements: { limits?: Record<string, number | null> }; usage: Usage };
type Event = { id: string; event_type: string; from_status?: string | null; to_status?: string | null; created_at: string; metadata?: Record<string, unknown> };
type Tab = "plans" | "tenants" | "history" | "gateways" | "billing";
type Invoice = { id: string; tenant_id: string; tenant_name: string; kind: string; amount_cents: string; currency: string; status: string; due_date: string | null; period_start: string | null; period_end: string | null; paid_at: string | null; created_at: string; payments: Array<{ id: string; status: string; amount_cents: string; method: string | null; paid_at: string | null }> };
type SelectedPlan = ReturnType<typeof normalizePlan>;
const fetcher = <T,>(url: string) => api<T>(url);
const money = (cents: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(cents / 100);
const eventLabel: Record<string, string> = { PLAN_CHANGED: "Plano alterado", SUSPENDED: "Suspenso", ACTIVE: "Ativo", CANCELED: "Cancelado", PAYMENT_APPROVED: "Pagamento aprovado", PAYMENT_REJECTED: "Pagamento rejeitado" };

export default function RootPlansPage() {
  const { data: session } = useSWR<PanelSession>("/me", fetcher, { revalidateOnFocus: false });
  const root = Boolean(session?.user.isRoot);
  const { data, error, mutate } = useSWR<{ plans: Plan[] }>(root ? "/root/saas/plans" : null, fetcher);
  const { data: catalog } = useSWR<Catalog>(root ? "/root/saas/catalog" : null, fetcher);
  const { data: tenantsData, error: tenantsError, mutate: mutateTenants } = useSWR<{ tenants: Tenant[] }>(root ? "/root/saas/tenants" : null, fetcher);
  const { data: eventsData, error: eventsError } = useSWR<{ events: Event[] }>(root ? "/root/saas/events" : null, fetcher);
  const [tab, setTab] = useState<Tab>("plans");
  // Carrega faturas apenas quando a aba está aberta: a lista é global ao SaaS.
  const { data: invoicesData, error: invoicesError } = useSWR<{ invoices: Invoice[] }>(root && tab === "billing" ? "/root/billing/invoices?limit=100" : null, fetcher);
  const [selected, setSelected] = useState<SelectedPlan | null>(null);
  const [archive, setArchive] = useState<Plan | null>(null);
  const [duplicate, setDuplicate] = useState<Plan | null>(null);
  const [choices, setChoices] = useState<Record<string, string>>({});
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState<string | null>(null);
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!selected) return;
    const f = new FormData(event.currentTarget);
    const payload = { code: String(f.get("code") ?? "").trim(), name: String(f.get("name") ?? "").trim(), description: String(f.get("description") ?? "").trim(), monthlyPriceCents: reaisToCents(String(f.get("price") ?? "0")), quarterlyPriceCents: reaisToCents(String(f.get("quarterlyPrice") ?? "0")), yearlyPriceCents: reaisToCents(String(f.get("yearlyPrice") ?? "0")), setupPriceCents: reaisToCents(String(f.get("setupPrice") ?? "0")), billingPeriodMonths: Number(f.get("billingPeriodMonths") ?? 1), trialDays: Number(f.get("trialDays") ?? 0), gracePeriodDays: Number(f.get("gracePeriodDays") ?? 0), features: selected.features, limits: selected.limits };
    try {
      if (selected.id) await api(`/root/saas/plans/${selected.id}`, { method: "PATCH", body: JSON.stringify(payload) });
      else { const response = await api<{ plan: Plan }>("/root/saas/plans", { method: "POST", body: JSON.stringify(payload) }); if (Object.keys(selected.features).length || Object.keys(selected.limits).length) await api(`/root/saas/plans/${response.plan.id}`, { method: "PATCH", body: JSON.stringify({ features: selected.features, limits: selected.limits }) }); setMessage("Plano criado. Edite-o para ajustar a matriz de features e limites."); }
      setSelected(null); await mutate();
    } catch (e) { setMessage(e instanceof Error ? e.message : "Não foi possível salvar."); }
  }
  // Real endpoints: POST /:id/archive and POST /:id/duplicate.
  async function planAction(plan: Plan, action: "archive" | "duplicate", code?: string, name?: string) {
    setBusy(plan.id); setMessage("");
    try { await api(`/root/saas/plans/${plan.id}/${action}`, { method: "POST", ...(action === "duplicate" ? { body: JSON.stringify({ code, name }) } : {}) }); setArchive(null); setDuplicate(null); setMessage(action === "archive" ? "Plano arquivado." : "Plano duplicado."); await mutate(); }
    catch (e) { setMessage(e instanceof Error ? e.message : "Não foi possível concluir a ação."); } finally { setBusy(null); }
  }
  async function tenantAction(id: string, action: string, planId?: string) { setBusy(id); try { await api(`/root/saas/tenants/${id}${action === "save" ? "/subscription" : `/subscription/${action}`}`, { method: "POST", body: action === "save" ? JSON.stringify({ planId }) : undefined }); await mutateTenants(); setMessage("Empresa atualizada com sucesso."); } catch (e) { setMessage(e instanceof Error ? e.message : "Não foi possível atualizar a empresa."); } finally { setBusy(null); } }
  const plans = data?.plans ?? []; const commercial = plans.filter((p) => p.status === "active" && !p.is_internal && p.code !== "LEGACY_UNLIMITED");
  if (!root) return <Shell><div className="card"><p>Esta área está disponível apenas para usuários ROOT.</p></div></Shell>;
  return <Shell><header className="pagehead" style={{ "--eyebrow": '"PAINEL · ROOT · SAAS"' } as React.CSSProperties}><div><h1>Planos e cobrança</h1><p>Planos, empresas, assinaturas, consumo e histórico.</p></div>{tab === "plans" && <button type="button" className="btn primary" onClick={() => setSelected(normalizePlan({ id: "", code: "", name: "", monthly_price_cents: 0, status: "active", is_internal: false, features: [], limits: [] }))}>Criar plano</button>}</header>
    <nav className="admin-actions mb-4" aria-label="Seções SaaS">{(["plans:Planos", "tenants:Empresas / Assinaturas / Consumo", "history:Histórico", "gateways:Gateways", "billing:Cobranças"] as const).map((x) => { const [key, label] = x.split(":") as [Tab, string]; return <button type="button" key={key} className={tab === key ? "btn primary" : "btn"} disabled={key === "gateways"} onClick={() => setTab(key)}>{label}{key === "gateways" ? " (tela própria)" : ""}</button>; })}</nav>
    {message && <p className="accent mb-4" role="status">{message}</p>}
    {tab === "plans" && (error ? <p className="error">Não foi possível carregar os planos.</p> : !data ? <div className="card">Carregando…</div> : plans.length === 0 ? <Empty>Nenhum plano.</Empty> : <section className="card admin-card"><div className="admin-table-wrap responsive-table-wrap"><table className="admin-table responsive-table"><thead><tr><th>Plano</th><th>Preço</th><th>Status</th><th>Ações</th></tr></thead><tbody>{plans.map((p) => <tr key={p.id}><td><strong>{p.name}</strong><span className="sub mono">{p.code}</span></td><td>{money(Number(p.monthly_price_cents))}</td><td>{p.status}</td><td><div className="admin-actions"><button type="button" className="btn" onClick={() => setSelected(normalizePlan(p))}>Editar</button><button type="button" className="btn" onClick={() => setDuplicate(p)}>Duplicar</button><button type="button" className="btn warn" onClick={() => setArchive(p)}>Arquivar</button></div></td></tr>)}</tbody></table></div></section>)}
    {tab === "tenants" && (tenantsError ? <p className="error">Não foi possível carregar as empresas.</p> : !tenantsData ? <div className="card">Carregando…</div> : tenantsData.tenants.length === 0 ? <Empty>Nenhuma empresa.</Empty> : <section className="card admin-card"><div className="admin-table-wrap responsive-table-wrap"><table className="admin-table responsive-table"><tbody>{tenantsData.tenants.map((t) => <tr key={t.id}><td>{t.name}</td><td>{t.plan_name ?? "Legacy Unlimited (atual)"}<select className="input mt-2" value={choices[t.id] ?? ""} onChange={(e) => setChoices({ ...choices, [t.id]: e.target.value })}><option value="">Selecionar plano</option>{commercial.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></td><td>{t.subscription_status ?? "Sem assinatura"}</td><td>Usuários: {formatUsage({ used: t.usage.MAX_USERS, limit: t.entitlements.limits?.MAX_USERS ?? null })} · WhatsApps: {formatUsage({ used: t.usage.MAX_WHATSAPP_CONNECTIONS, limit: t.entitlements.limits?.MAX_WHATSAPP_CONNECTIONS ?? null })} · IA: {formatUsage({ used: t.usage.MAX_AI_INTERACTIONS, limit: t.entitlements.limits?.MAX_AI_INTERACTIONS ?? null })}</td><td><button type="button" className="btn primary" disabled={busy === t.id || !choices[t.id]} onClick={() => void tenantAction(t.id, "save", choices[t.id])}>Salvar plano</button><button type="button" className="btn warn" disabled={busy === t.id} onClick={() => void tenantAction(t.id, "suspend")}>Suspender</button><button type="button" className="btn" disabled={busy === t.id} onClick={() => void tenantAction(t.id, "reactivate")}>Reativar</button><button type="button" className="btn" disabled={busy === t.id} onClick={() => void tenantAction(t.id, "cancel")}>Cancelar</button></td></tr>)}</tbody></table></div></section>)}
    {tab === "history" && (eventsError ? <p className="error">Não foi possível carregar o histórico.</p> : !eventsData ? <div className="card">Carregando…</div> : eventsData.events.length === 0 ? <Empty>Nenhum evento.</Empty> : <section className="card admin-card"><h2>Histórico</h2>{eventsData.events.map((e) => <p key={e.id} className="sub">{e.created_at} · {eventLabel[e.event_type] ?? e.event_type}{e.from_status || e.to_status ? ` (${e.from_status ?? "—"} → ${e.to_status ?? "—"})` : ""}</p>)}</section>)}
    {tab === "billing" && (invoicesError ? <p className="error">Não foi possível carregar as cobranças.</p> : !invoicesData ? <div className="card">Carregando…</div> : invoicesData.invoices.length === 0 ? <Empty>Nenhuma cobrança emitida.</Empty> : <section className="card admin-card"><div className="admin-table-wrap responsive-table-wrap"><table className="admin-table responsive-table"><thead><tr><th>Empresa</th><th>Competência</th><th>Valor</th><th>Status</th><th>Pagamento</th></tr></thead><tbody>{invoicesData.invoices.map((i) => { const paid = i.payments.find((p) => p.status === "paid"); return <tr key={i.id}><td><strong>{i.tenant_name}</strong><span className="sub mono">{i.kind}</span></td><td>{i.period_start ? new Date(i.period_start).toLocaleDateString("pt-BR") : "—"}{i.period_end ? ` – ${new Date(i.period_end).toLocaleDateString("pt-BR")}` : ""}<span className="sub">{i.due_date ? `vence ${new Date(i.due_date).toLocaleDateString("pt-BR")}` : "sem vencimento"}</span></td><td>{money(Number(i.amount_cents))}</td><td>{i.status}</td><td>{paid ? `${paid.method ?? "—"} · ${paid.paid_at ? new Date(paid.paid_at).toLocaleDateString("pt-BR") : "—"}` : i.payments.length ? `${i.payments.length} tentativa(s)` : "—"}</td></tr>; })}</tbody></table></div></section>)}
    {selected && <ModalDialog labelledBy="plan-title" onClose={() => setSelected(null)}><form className="card admin-card" onSubmit={save}><h2 id="plan-title">{selected.id ? "Editar plano" : "Criar plano"}</h2>{(["code:Código:text", "name:Nome:text", "description:Descrição:text", "price:Preço mensal (R$):number", "quarterlyPrice:Preço trimestral (R$):number", "yearlyPrice:Preço anual (R$):number", "setupPrice:Setup (R$):number", "billingPeriodMonths:Periodicidade (meses):number", "trialDays:Trial (dias):number", "gracePeriodDays:Carência (dias):number"] as const).map((x) => { const [name, label, type] = x.split(":"); const value = name === "price" ? selected.monthlyPriceCents / 100 : name === "setupPrice" ? selected.setupPriceCents / 100 : selected[name as keyof SelectedPlan]; return <label className="field" key={name}><span className="label">{label}</span><input className="input" name={name} type={type} defaultValue={String(value ?? "")} required={name !== "description"} /></label>; })}<div className="border-y border-[var(--border)] py-3"><span className="label">Features e limites</span>{(catalog?.feature_catalog ?? []).map((f) => <label className="field mt-2" key={f.feature_key}><span>{f.label}</span><input type="checkbox" checked={selected.features[f.feature_key] === true} onChange={(e) => setSelected({ ...selected, features: { ...selected.features, [f.feature_key]: e.target.checked } })} /></label>)}{(catalog?.limit_catalog ?? []).map((l) => <label className="field mt-2" key={l.limit_key}><span>{l.label}</span><input className="input" type="number" value={selected.limits[l.limit_key] ?? ""} onChange={(e) => setSelected({ ...selected, limits: { ...selected.limits, [l.limit_key]: e.target.value === "" ? null : Number(e.target.value) } })} /></label>)}</div><div className="admin-actions"><button type="submit" className="btn primary">Salvar</button><button type="button" className="btn" onClick={() => setSelected(null)}>Cancelar</button></div></form></ModalDialog>}
    {archive && <ModalDialog labelledBy="archive-title" onClose={() => setArchive(null)}><div className="card"><h2 id="archive-title">Arquivar plano?</h2><p>Esta ação será registrada e o plano deixará de ser comercializado.</p><button type="button" className="btn warn" onClick={() => void planAction(archive, "archive")}>Confirmar arquivamento</button></div></ModalDialog>}
    {duplicate && <ModalDialog labelledBy="duplicate-title" onClose={() => setDuplicate(null)}><form className="card" onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); const payload = duplicatePlanPayload(String(f.get("code") ?? ""), String(f.get("name") ?? "")); void planAction(duplicate, "duplicate", payload.code, "name" in payload ? payload.name : undefined); }}><h2 id="duplicate-title">Duplicar plano</h2><input className="input" name="code" placeholder="Novo código" required /><input className="input mt-2" name="name" placeholder="Novo nome (opcional)" /><button type="submit" className="btn primary mt-2">Duplicar</button></form></ModalDialog>}
  </Shell>;
}
