import type { FastifyInstance } from "fastify";
import type { PoolClient } from "pg";
import { z } from "zod";
import { db } from "../../db/client.js";
import { requirePermission, requireRoot, requireWorkspace } from "../../auth/session.js";
import { getUsageDashboard } from "../../billing/alerts.js";
import { getBillingHistory } from "../../billing/invoices.js";
import { getBillingSettings, invalidateBillingSettingsCache } from "../../billing/settings.js";
import { getRootBillingMetrics } from "../../billing/metrics.js";
import { listPlanPrices, upsertPlanPrice, contractPlanForTenant } from "../../billing/contracts.js";
import { invalidatePricingRuleCache } from "../../billing/pricing.js";
import { listProviders, saveEncryptedCredentials, updateCommercialConfig, disconnect, setEnabled } from "../../billing/providers/store.js";
import { beginMercadoPagoOAuth, completeMercadoPagoOAuth, refreshMercadoPagoToken, testMercadoPagoConnection } from "../../billing/providers/mercadopago-oauth.js";
import { createChargeForInvoice, type ChargeDeps } from "../../billing/charges.js";

const uuid=z.string().uuid();
const credit=z.object({enabled:z.boolean(),limitType:z.enum(["FIXED","UNLIMITED"]),monthlySpendingLimitCents:z.number().int().positive().nullable().optional(),confirmUnlimited:z.boolean().optional()}).strict();
const cycles=z.enum(["MONTHLY","QUARTERLY","YEARLY"]);
const providerEnvironment=z.enum(["sandbox","production"]);
const audit=async(c:Pick<PoolClient, "query">, actor:string, action:string, type:string, id:string|null, before:unknown, after:unknown, tenant:string|null=null)=>c.query("INSERT INTO audit_logs(actor_user_id,workspace_id,actor_scope,action,resource_type,resource_id,metadata) VALUES($1,$2,'root',$3,$4,$5,$6)",[actor,tenant,action,type,id,{before,after}]);
async function tx<T>(f:(c:PoolClient)=>Promise<T>){const c=await db.connect();try{await c.query("BEGIN");const v=await f(c);await c.query("COMMIT");return v}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
export type BillingOAuthDependencies = {
  fetchImpl?: typeof fetch;
  chargeDeps?: ChargeDeps;
};

export async function registerBillingRoutes(app:FastifyInstance, dependencies: BillingOAuthDependencies = {}){
 const mercadopagoCode="mercadopago";
 const safeError=(error:unknown)=>Object.assign(new Error(error instanceof Error ? error.message : "Operação Mercado Pago falhou"),{statusCode:400});
 app.get("/root/billing/settings",async r=>{await requireRoot(r);return {settings:await getBillingSettings()}});
 app.post("/root/billing/invoices/:invoiceId/charge",async r=>{const root=await requireRoot(r);const invoiceId=uuid.parse((r.params as {invoiceId:string}).invoiceId);const body=z.object({method:z.string().trim().min(1)}).strict().parse(r.body);const charged=await createChargeForInvoice(invoiceId,body.method,dependencies.chargeDeps);const safe={invoiceId:charged.invoiceId,externalId:charged.externalId,status:charged.status,reference:charged.reference};await audit(db,root.userId,"billing.invoice.charge","invoice",invoiceId,null,safe);return {charge:safe};});
 app.get("/billing/usage-dashboard",async r=>{const s=await requireWorkspace(r);const c=await db.connect();try{return {dashboard:await getUsageDashboard(c,s.tenantId)}}finally{c.release()}});
 app.get("/billing/history",async r=>{const s=await requireWorkspace(r);const q=z.object({limit:z.coerce.number().int().min(1).max(100).default(20)}).parse(r.query);return {history:await getBillingHistory(s.tenantId,q.limit)}});
 app.get("/billing/usage-credit",async r=>{const s=await requireWorkspace(r);const [x,settings]=await Promise.all([db.query("SELECT enabled,limit_type,monthly_spending_limit_cents,confirmed_unlimited_at FROM tenant_usage_credit_settings WHERE tenant_id=$1",[s.tenantId]),getBillingSettings()]);return {setting:x.rows[0]??{enabled:false,limit_type:"FIXED",monthly_spending_limit_cents:null,confirmed_unlimited_at:null},allowed:{suggested:settings.credit_suggested_cents,min:settings.credit_min_cents,max:settings.credit_max_cents,allowCustom:settings.allow_custom_credit,allowUnlimited:settings.allow_unlimited_credit}}});
 app.put("/billing/usage-credit",async r=>{const s=await requirePermission(r,"billing.manage");const b=credit.parse(r.body);const settings=await getBillingSettings();if(b.limitType==="UNLIMITED"&&b.enabled&&(!settings.allow_unlimited_credit||b.confirmUnlimited!==true))throw Object.assign(new Error("Confirmação obrigatória"),{statusCode:400});if(b.enabled&&b.limitType==="FIXED"&&(!settings.allow_custom_credit||b.monthlySpendingLimitCents==null||b.monthlySpendingLimitCents<settings.credit_min_cents||b.monthlySpendingLimitCents>settings.credit_max_cents))throw Object.assign(new Error("Limite fora da faixa permitida"),{statusCode:400});return tx(async c=>{const before=(await c.query("SELECT * FROM tenant_usage_credit_settings WHERE tenant_id=$1",[s.tenantId])).rows[0]??null;const x=await c.query("INSERT INTO tenant_usage_credit_settings(tenant_id,enabled,limit_type,monthly_spending_limit_cents,confirmed_unlimited_at,updated_by_user_id) VALUES($1,$2,$3,$4,CASE WHEN $2 AND $3='UNLIMITED' THEN now() ELSE NULL END,$5) ON CONFLICT(tenant_id) DO UPDATE SET enabled=EXCLUDED.enabled,limit_type=EXCLUDED.limit_type,monthly_spending_limit_cents=EXCLUDED.monthly_spending_limit_cents,confirmed_unlimited_at=EXCLUDED.confirmed_unlimited_at,updated_by_user_id=EXCLUDED.updated_by_user_id,updated_at=now() RETURNING *",[s.tenantId,b.enabled,b.limitType,b.enabled&&b.limitType==="FIXED"?b.monthlySpendingLimitCents:null,s.userId]);await c.query("INSERT INTO subscription_events(tenant_id,subscription_id,event_type,actor_user_id,metadata) SELECT $1,id,'USAGE_CREDIT_UPDATED',$2,$3 FROM tenant_subscriptions WHERE tenant_id=$1",[s.tenantId,s.userId,{before,after:x.rows[0]}]);await audit(c,s.userId,"billing.usage_credit.update","usage_credit",s.tenantId,before,x.rows[0],s.tenantId);return {setting:x.rows[0]}})});
 app.post("/root/billing/tenants/:tenantId/contract",async r=>{const root=await requireRoot(r);const b=z.object({planId:uuid,billingCycle:cycles}).parse(r.body);const tenantId=uuid.parse((r.params as Record<string, string>).tenantId);const subscription=await contractPlanForTenant(tenantId,b.planId,b.billingCycle,root.userId);await audit(db,root.userId,"billing.contract.create","subscription",subscription.id,null,subscription,tenantId);return {subscription};});
 /**
  * Conta de cobranca do tenant (§ pagador). O ROOT e a autoridade: e ele quem
  * contrata plano e concede bonus, entao e ele quem registra o pagador.
  *
  * Sem esta conta, charges.ts:47 envia o pagamento ao gateway sem document/email
  * e reconciler.ts:60 nao consegue fixar o provider preferencial da fatura,
  * caindo no primeiro provedor conectado. A tabela existia desde 0132 e nunca
  * teve produtor.
  */
 app.get("/root/billing/tenants/:tenantId/account",async r=>{await requireRoot(r);const tenantId=uuid.parse((r.params as Record<string, string>).tenantId);const x=await db.query("SELECT id,tenant_id,provider_id,external_customer_id,document,email,created_at,updated_at FROM billing_accounts WHERE tenant_id=$1",[tenantId]);return {account:x.rows[0]??null};});
 app.put("/root/billing/tenants/:tenantId/account",async r=>{const root=await requireRoot(r);const tenantId=uuid.parse((r.params as Record<string, string>).tenantId);const b=z.object({providerCode:z.string().trim().min(1),environment:providerEnvironment.default("production"),document:z.string().trim().min(1).max(32).nullable().optional(),email:z.string().trim().email().max(320).nullable().optional(),externalCustomerId:z.string().trim().max(200).nullable().optional()}).strict().parse(r.body);
  return tx(async c=>{
   const tenant=(await c.query("SELECT id FROM tenants WHERE id=$1",[tenantId])).rows[0];
   if(!tenant)throw Object.assign(new Error("Workspace não encontrado"),{statusCode:404});
   const provider=(await c.query<{id:string}>("SELECT id FROM billing_providers WHERE code=$1 AND environment=$2",[b.providerCode,b.environment])).rows[0];
   if(!provider)throw Object.assign(new Error("Provedor de cobrança não encontrado"),{statusCode:404,code:"BILLING_PROVIDER_NOT_FOUND"});
   const before=(await c.query("SELECT * FROM billing_accounts WHERE tenant_id=$1",[tenantId])).rows[0]??null;
   const x=await c.query(`INSERT INTO billing_accounts(tenant_id,provider_id,external_customer_id,document,email)
     VALUES($1,$2,$3,$4,$5)
     ON CONFLICT(tenant_id) DO UPDATE SET provider_id=EXCLUDED.provider_id,external_customer_id=EXCLUDED.external_customer_id,document=EXCLUDED.document,email=EXCLUDED.email,updated_at=now()
     RETURNING id,tenant_id,provider_id,external_customer_id,document,email,created_at,updated_at`,
    [tenantId,provider.id,b.externalCustomerId??null,b.document??null,b.email??null]);
   await audit(c,root.userId,"billing.account.upsert","billing_account",x.rows[0].id,before,x.rows[0],tenantId);
   return {account:x.rows[0]};
  });
 });
 /** Faturas para a aba Cobrancas do painel ROOT, que ate entao nao tinha endpoint de consulta. */
 app.get("/root/billing/invoices",async r=>{await requireRoot(r);const q=z.object({tenantId:uuid.optional(),status:z.string().trim().max(40).optional(),limit:z.coerce.number().int().min(1).max(200).default(50)}).parse(r.query);
  const x=await db.query(`SELECT i.id,i.tenant_id,t.name tenant_name,i.subscription_id,i.provider_id,i.external_id,i.kind,i.amount_cents,i.currency,i.status,i.due_date,i.period_start,i.period_end,i.paid_at,i.created_at,
    COALESCE((SELECT json_agg(json_build_object('id',p.id,'status',p.status,'amount_cents',p.amount_cents,'method',p.method,'paid_at',p.paid_at) ORDER BY p.created_at DESC) FROM payments p WHERE p.invoice_id=i.id),'[]'::json) payments
    FROM invoices i JOIN tenants t ON t.id=i.tenant_id
    WHERE ($1::uuid IS NULL OR i.tenant_id=$1) AND ($2::text IS NULL OR i.status=$2)
    ORDER BY i.created_at DESC LIMIT $3`,[q.tenantId??null,q.status??null,q.limit]);
  return {invoices:x.rows};});
 app.post("/root/billing/tenants/:tenantId/bonus",async r=>{const root=await requireRoot(r);const b=z.object({amount:z.number().int().positive(),reason:z.string().trim().min(1).max(500),expiresAt:z.string().datetime().nullable().optional()}).parse(r.body);const tenantId=uuid.parse((r.params as Record<string, string>).tenantId);return tx(async c=>{const sub=(await c.query("SELECT id FROM tenant_subscriptions WHERE tenant_id=$1 FOR UPDATE",[tenantId])).rows[0];if(!sub)throw Object.assign(new Error("Assinatura não encontrada"),{statusCode:404});const period=(await c.query("SELECT id FROM usage_periods WHERE tenant_id=$1 AND status='OPEN' ORDER BY sequence DESC LIMIT 1 FOR UPDATE",[tenantId])).rows[0];if(!period)throw Object.assign(new Error("Período aberto não encontrado"),{statusCode:409});const g=(await c.query("INSERT INTO usage_grants(tenant_id,usage_period_id,amount,reason,granted_by_user_id,expires_at) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",[tenantId,period.id,b.amount,b.reason,root.userId,b.expiresAt??null])).rows[0];await c.query("UPDATE usage_periods SET bonus_granted=bonus_granted+$2,updated_at=now() WHERE id=$1",[period.id,b.amount]);await c.query("INSERT INTO subscription_events(tenant_id,subscription_id,event_type,actor_user_id,metadata) VALUES($1,$2,'BONUS_GRANTED',$3,$4)",[tenantId,sub.id,root.userId,{grant:g}]);await audit(c,root.userId,"billing.bonus.grant","usage_grant",g.id,null,g,tenantId);return {grant:g};});});
 app.get("/root/billing/pricing/rule",async r=>{await requireRoot(r);return {rule:(await db.query("SELECT * FROM ai_pricing_rules WHERE active=true LIMIT 1")).rows[0]??null};});
 app.get("/root/billing/pricing/models",async r=>{await requireRoot(r);return {prices:(await db.query("SELECT * FROM ai_model_prices WHERE effective_from<=now() AND (effective_to IS NULL OR effective_to>now()) ORDER BY model")).rows};});
 app.post("/root/billing/pricing/models",async r=>{const root=await requireRoot(r);const b=z.object({model:z.string().trim().min(1),inputPricePerMillionMicros:z.number().int().nonnegative(),outputPricePerMillionMicros:z.number().int().nonnegative(),cachedInputPricePerMillionMicros:z.number().int().nonnegative().nullable().optional(),effectiveFrom:z.string().datetime().optional(),effectiveTo:z.string().datetime().nullable().optional()}).parse(r.body);return tx(async c=>{const x=(await c.query("INSERT INTO ai_model_prices(model,input_price_per_million_micros,output_price_per_million_micros,cached_input_price_per_million_micros,effective_from,effective_to) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",[b.model,b.inputPricePerMillionMicros,b.outputPricePerMillionMicros,b.cachedInputPricePerMillionMicros??null,b.effectiveFrom??new Date().toISOString(),b.effectiveTo??null])).rows[0];await audit(c,root.userId,"billing.model_price.create","ai_model_price",x.id,null,x);return {price:x};});});
 app.post("/root/billing/pricing/rule",async r=>{const root=await requireRoot(r);const b=z.object({strategy:z.enum(["COST_PLUS_MARKUP","FIXED_PER_INTERACTION","CUSTOM"]),markupBps:z.number().int().min(0).optional(),fixedPricePerInteractionCents:z.number().int().nonnegative().optional(),config:z.record(z.unknown()).default({})}).parse(r.body);if(b.strategy==="COST_PLUS_MARKUP"&&b.markupBps==null||b.strategy==="FIXED_PER_INTERACTION"&&b.fixedPricePerInteractionCents==null)throw Object.assign(new Error("Regra incompleta"),{statusCode:400});return tx(async c=>{await c.query("UPDATE ai_pricing_rules SET active=false WHERE active=true");const x=(await c.query("INSERT INTO ai_pricing_rules(version,strategy,markup_bps,fixed_price_per_interaction_cents,config,active,created_by_user_id) SELECT COALESCE(max(version),0)+1,$1,$2,$3,$4,true,$5 FROM ai_pricing_rules RETURNING *",[b.strategy,b.markupBps??null,b.fixedPricePerInteractionCents??null,b.config,root.userId])).rows[0];invalidatePricingRuleCache();await audit(c,root.userId,"billing.pricing_rule.create","ai_pricing_rule",x.id,null,x);return {rule:x};});});
 app.patch("/root/billing/settings",async r=>{const root=await requireRoot(r);const allowed=["default_rollover_rate_bps","default_rollover_max_percentage_bps","default_rollover_expiration_periods","usd_brl_rate_micros","credit_min_cents","credit_max_cents","credit_suggested_cents","allow_custom_credit","allow_unlimited_credit","quota_alert_thresholds_bps","credit_alert_thresholds_bps","min_overage_estimate_cents","reservation_ttl_minutes","webhook_tolerance_seconds"];const b=z.record(z.unknown()).parse(r.body);const keys=Object.keys(b);if(keys.some(k=>!allowed.includes(k)))throw Object.assign(new Error("Campo não permitido"),{statusCode:400});return tx(async c=>{const before=await getBillingSettings(c);if(b.credit_min_cents!=null&&b.credit_max_cents!=null&&b.credit_min_cents>b.credit_max_cents)throw Object.assign(new Error("Faixa inválida"),{statusCode:400});const set=keys.map((k,i)=>`${k}=$${i+2}`).join(",");const x=await c.query(`UPDATE billing_settings SET ${set},updated_at=now() WHERE id=$1::boolean RETURNING *`,[true,...keys.map(k=>b[k])]);invalidateBillingSettingsCache();await audit(c,root.userId,"billing.settings.update","billing_settings","true",before,x.rows[0]);return {settings:x.rows[0]}})});
 app.get("/root/billing/metrics",async r=>{await requireRoot(r);const q=z.object({tenantId:uuid.optional(),planId:uuid.optional(),start:z.string().optional(),end:z.string().optional()}).parse(r.query);return {metrics:await getRootBillingMetrics(q)}});
 app.get("/root/billing/plans/:id/prices",async r=>{await requireRoot(r);return {prices:await listPlanPrices(uuid.parse((r.params as Record<string, string>).id))}});
 app.put("/root/billing/plans/:id/prices/:cycle",async r=>{const root=await requireRoot(r);const b=z.object({basePriceCents:z.number().int().nonnegative(),discountType:z.enum(["PERCENT","FIXED"]).nullable().optional(),discountValue:z.number().int().nonnegative().nullable().optional(),currency:z.string().regex(/^[A-Z]{3}$/)}).parse(r.body);return tx(async c=>{const p=await upsertPlanPrice(c,{planId:uuid.parse((r.params as Record<string, string>).id),billingCycle:cycles.parse((r.params as Record<string, string>).cycle),...b},root.userId);await audit(c,root.userId,"billing.plan_price.update","plan_price",p.id,null,p);return {price:p}})});
 app.get("/root/billing/providers",async r=>{await requireRoot(r);return {providers:await listProviders()}});
 app.post("/root/billing/providers/:environment/oauth/begin",async r=>{const root=await requireRoot(r);const env=providerEnvironment.parse((r.params as Record<string, string>).environment);const b=z.object({redirectUri:z.string().url()}).strict().parse(r.body);try{return await beginMercadoPagoOAuth(mercadopagoCode,env,root.userId,b.redirectUri,dependencies.fetchImpl)}catch(error){throw safeError(error)}});
 app.get("/billing/providers/mercadopago/oauth/callback",async (r,reply)=>{const q=z.object({state:z.string().min(1),code:z.string().min(1)}).parse(r.query);try{await completeMercadoPagoOAuth(q.state,q.code,dependencies.fetchImpl);return reply.redirect("/root/saas/gateways?mercadopago=connected")}catch{ return reply.redirect("/root/saas/gateways?mercadopago=error") }});
 app.post("/root/billing/providers/:environment/oauth/refresh",async r=>{await requireRoot(r);const env=providerEnvironment.parse((r.params as {environment: unknown}).environment);try{return {provider:await refreshMercadoPagoToken(mercadopagoCode,env,dependencies.fetchImpl)}}catch(error){throw safeError(error)}});
 app.post("/root/billing/providers/:environment/test-connection",async r=>{await requireRoot(r);const env=providerEnvironment.parse((r.params as {environment: unknown}).environment);try{return {connection:await testMercadoPagoConnection(mercadopagoCode,env,dependencies.fetchImpl)}}catch(error){throw safeError(error)}});
 app.put("/root/billing/providers/:code/:environment/credentials",async r=>{const root=await requireRoot(r);const params=r.params as {code: string; environment: string};const b=z.object({credentials:z.record(z.unknown())}).strict().parse(r.body);return {provider:await saveEncryptedCredentials(params.code,providerEnvironment.parse(params.environment),b.credentials,root.userId)}});
 app.patch("/root/billing/providers/:code/:environment/config",async r=>{await requireRoot(r);const params=r.params as {code: string; environment: string};const b=z.record(z.unknown()).parse(r.body);return {provider:await updateCommercialConfig(params.code,providerEnvironment.parse(params.environment),b)}});
 app.post("/root/billing/providers/:code/:environment/enabled",async r=>{const root=await requireRoot(r);const params=r.params as {code: string; environment: string};const b=z.object({enabled:z.boolean()}).strict().parse(r.body);try{return {provider:await setEnabled(params.code,providerEnvironment.parse(params.environment),b.enabled,root.userId)}}catch(error){throw safeError(error)}});
 app.post("/root/billing/providers/:code/:environment/disconnect",async r=>{const root=await requireRoot(r);const params=r.params as {code: string; environment: string};const b=z.object({confirm:z.literal(true)}).parse(r.body);void b;const provider=await disconnect(params.code,providerEnvironment.parse(params.environment),root.userId);return {provider,remoteRevocation:"Mercado Pago não oferece API para revogação remota. Para revogar totalmente o acesso, o vendedor deve fazê-lo manualmente em sua conta do Mercado Pago, em Configurações > Suas integrações."}});
}
