import type { FastifyInstance } from "fastify";
import type { PoolClient } from "pg";
import { z } from "zod";
import { db } from "../../db/client.js";
import { requirePermission, requireRoot, requireWorkspace } from "../../auth/session.js";
import { getUsageDashboard } from "../../billing/alerts.js";
import { getBillingHistory } from "../../billing/invoices.js";
import { getBillingSettings, invalidateBillingSettingsCache } from "../../billing/settings.js";
import { getRootBillingMetrics } from "../../billing/metrics.js";
import { listPlanPrices, upsertPlanPrice, contractPlanForTenant } from "../../billing/contracts.js";
import { invalidatePricingRuleCache } from "../../billing/pricing.js";
import { listProviders, saveEncryptedCredentials, saveWebhookSecret, updateCommercialConfig, disconnect, setEnabled } from "../../billing/providers/store.js";
import { beginMercadoPagoOAuth, completeMercadoPagoOAuth, refreshMercadoPagoToken, testMercadoPagoConnection } from "../../billing/providers/mercadopago-oauth.js";
import { createChargeForInvoice, type ChargeDeps } from "../../billing/charges.js";
import { createCreditPackPurchase, listCreditPackPurchases, creditPackBalance, AI_CREDIT_PACK_SKU, AI_CREDIT_PACK_CREDITS, AI_CREDIT_PACK_PRICE_CENTS } from "../../billing/credit-packs.js";
import { assertHomologatedProvider, providerNotHomologated } from "../../billing/providers/homologation.js";
import { startMonthlyPixMandate, getMonthlyPixMandate, stopMonthlyPixMandate } from "../../billing/efipay-mandates.js";

const uuid=z.string().uuid();
const credit=z.object({enabled:z.boolean(),limitType:z.enum(["FIXED","UNLIMITED"]),monthlySpendingLimitCents:z.number().int().positive().nullable().optional(),confirmUnlimited:z.boolean().optional()}).strict();
const cycles=z.enum(["MONTHLY","QUARTERLY","YEARLY"]);
const providerEnvironment=z.enum(["sandbox","production"]);
const audit=async(c:Pick<PoolClient, "query">, actor:string, action:string, type:string, id:string|null, before:unknown, after:unknown, tenant:string|null=null)=>c.query("INSERT INTO audit_logs(actor_user_id,workspace_id,actor_scope,action,resource_type,resource_id,metadata) VALUES($1,$2,'root',$3,$4,$5,$6)",[actor,tenant,action,type,id,{before,after}]);
async function tx<T>(f:(c:PoolClient)=>Promise<T>){const c=await db.connect();try{await c.query("BEGIN");const v=await f(c);await c.query("COMMIT");return v}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
export type BillingOAuthDependencies = {
  fetchImpl?: typeof fetch;
  chargeDeps?: ChargeDeps;
};

export async function registerBillingRoutes(app:FastifyInstance, dependencies: BillingOAuthDependencies = {}){
 const mercadopagoCode="mercadopago";
 const safeError=(error:unknown)=>Object.assign(new Error(error instanceof Error ? error.message : "Operação Mercado Pago falhou"),{statusCode:400});
 app.get("/root/billing/settings",async r=>{await requireRoot(r);return {settings:await getBillingSettings()}});
 app.post("/root/billing/invoices/:invoiceId/charge",async r=>{const root=await requireRoot(r);const invoiceId=uuid.parse((r.params as {invoiceId:string}).invoiceId);const body=z.object({method:z.string().trim().min(1)}).strict().parse(r.body);const charged=await createChargeForInvoice(invoiceId,body.method,dependencies.chargeDeps);const safe={invoiceId:charged.invoiceId,externalId:charged.externalId,status:charged.status,reference:charged.reference};await audit(db,root.userId,"billing.invoice.charge","invoice",invoiceId,null,safe);return {charge:safe};});
 app.post("/billing/invoices/:invoiceId/charge",async r=>{const s=await requirePermission(r,"billing.manage");const invoiceId=uuid.parse((r.params as {invoiceId:string}).invoiceId);const body=z.object({method:z.literal("pix")}).strict().parse(r.body);const own=(await db.query("SELECT id FROM invoices WHERE id=$1 AND tenant_id=$2 AND status IN ('pending','open','overdue')",[invoiceId,s.tenantId])).rows[0];if(!own)throw Object.assign(new Error("Fatura não encontrada"),{statusCode:404});const charged=await createChargeForInvoice(invoiceId,body.method,dependencies.chargeDeps,{allowSuspended:true,expectedTenantId:s.tenantId});return {charge:{invoiceId:charged.invoiceId,id:charged.externalId,status:charged.status,qr_code:charged.qr_code??null,ticket_url:charged.ticket_url??null}};});
 app.get("/billing/invoices/:invoiceId/payment",async r=>{const s=await requirePermission(r,"billing.manage");const invoiceId=uuid.parse((r.params as {invoiceId:string}).invoiceId);const x=await db.query("SELECT i.id AS \"invoiceId\",p.external_id AS id,p.status,p.metadata->'point_of_interaction'->'transaction_data'->>'qr_code' AS qr_code,p.metadata->'point_of_interaction'->'transaction_data'->>'ticket_url' AS ticket_url FROM invoices i LEFT JOIN LATERAL (SELECT * FROM payments WHERE invoice_id=i.id AND method='pix' ORDER BY created_at DESC LIMIT 1) p ON true WHERE i.id=$1 AND i.tenant_id=$2",[invoiceId,s.tenantId]);if(!x.rows[0])throw Object.assign(new Error("Fatura não encontrada"),{statusCode:404});return {charge:x.rows[0].id?x.rows[0]:null};});
 // Compra de pacote de créditos de IA: preço/quantidade são constantes do
 // SERVIDOR (o corpo aceita apenas idempotencyKey; strict() rejeita price/
 // credits). A fatura nasce pendente e a cobrança PIX reutiliza a rota
 // /billing/invoices/:invoiceId/charge; a concessão só ocorre no webhook pago.
 app.post("/billing/ai-credit-packs",async r=>{const s=await requirePermission(r,"billing.manage");const b=z.object({idempotencyKey:uuid}).strict().parse(r.body);const created=await createCreditPackPurchase(s.tenantId,b.idempotencyKey);await audit(db,s.userId,"billing.credit_pack.purchase","ai_credit_purchase",created.purchase.id,null,{sku:created.purchase.sku,invoiceId:created.invoice.id,priceCents:created.purchase.priceCents},s.tenantId);return {purchase:created.purchase,invoice:created.invoice};});
 app.get("/billing/ai-credit-packs",async r=>{const s=await requireWorkspace(r);const q=z.object({page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(100).default(25)}).parse(r.query);const list=await listCreditPackPurchases(s.tenantId,q.page,q.limit);return {sku:{sku:AI_CREDIT_PACK_SKU,credits:AI_CREDIT_PACK_CREDITS,priceCents:AI_CREDIT_PACK_PRICE_CENTS,currency:"BRL"},purchases:list.purchases,page:list.page,limit:list.limit};});
 app.get("/billing/ai-credit-packs/balance",async r=>{const s=await requireWorkspace(r);return {balance:await creditPackBalance(s.tenantId)}});
 // Mandato Pix Automato (Efí): opt-in mensal do SKU de créditos de IA. Preço e
 // quantidade são constantes do SERVIDOR — o POST não aceita corpo (o strict
 // vazio rejeita price/credits). O DELETE só interrompe NOVAS cobranças locais:
 // a API da Efí não expõe cancelamento do `rec`, então a resposta diz que a
 // revogação da autorização permanece com o pagador (app do banco).
 app.get("/billing/ai-credit-packs/pix-automatic",async r=>{const s=await requireWorkspace(r);return {mandate:await getMonthlyPixMandate(s.tenantId)}});
 app.post("/billing/ai-credit-packs/pix-automatic",async r=>{const s=await requirePermission(r,"billing.manage");z.object({}).strict().nullish().parse(r.body);return {mandate:await startMonthlyPixMandate(s.tenantId,s.userId)}});
 app.delete("/billing/ai-credit-packs/pix-automatic",async r=>{const s=await requirePermission(r,"billing.manage");const mandate=await stopMonthlyPixMandate(s.tenantId,s.userId);return {mandate,remoteRevocation:"A Efí não oferece API para cancelar a recorrência. Novas cobranças deixam de ser emitidas por este sistema; para revogar a autorização, o pagador deve cancelar o Pix Automato no app do banco."}});
 app.get("/billing/usage-dashboard",async r=>{const s=await requireWorkspace(r);const c=await db.connect();try{return {dashboard:await getUsageDashboard(c,s.tenantId)}}finally{c.release()}});
 app.get("/billing/history",async r=>{const s=await requireWorkspace(r);const q=z.object({limit:z.coerce.number().int().min(1).max(100).default(20)}).parse(r.query);return {history:await getBillingHistory(s.tenantId,q.limit)}});
 app.get("/billing/usage-credit",async r=>{const s=await requireWorkspace(r);const [x,settings]=await Promise.all([db.query("SELECT enabled,limit_type,monthly_spending_limit_cents,confirmed_unlimited_at FROM tenant_usage_credit_settings WHERE tenant_id=$1",[s.tenantId]),getBillingSettings()]);return {setting:x.rows[0]??{enabled:false,limit_type:"FIXED",monthly_spending_limit_cents:null,confirmed_unlimited_at:null},allowed:{suggested:settings.credit_suggested_cents,min:settings.credit_min_cents,max:settings.credit_max_cents,allowCustom:settings.allow_custom_credit,allowUnlimited:settings.allow_unlimited_credit}}});
 app.put("/billing/usage-credit",async r=>{const s=await requirePermission(r,"billing.manage");const b=credit.parse(r.body);const settings=await getBillingSettings();if(b.limitType==="UNLIMITED"&&b.enabled&&(!settings.allow_unlimited_credit||b.confirmUnlimited!==true))throw Object.assign(new Error("Confirmação obrigatória"),{statusCode:400});if(b.enabled&&b.limitType==="FIXED"&&(!settings.allow_custom_credit||b.monthlySpendingLimitCents==null||b.monthlySpendingLimitCents<settings.credit_min_cents||b.monthlySpendingLimitCents>settings.credit_max_cents))throw Object.assign(new Error("Limite fora da faixa permitida"),{statusCode:400});return tx(async c=>{const before=(await c.query("SELECT * FROM tenant_usage_credit_settings WHERE tenant_id=$1",[s.tenantId])).rows[0]??null;const x=await c.query("INSERT INTO tenant_usage_credit_settings(tenant_id,enabled,limit_type,monthly_spending_limit_cents,confirmed_unlimited_at,updated_by_user_id) VALUES($1,$2,$3,$4,CASE WHEN $2 AND $3='UNLIMITED' THEN now() ELSE NULL END,$5) ON CONFLICT(tenant_id) DO UPDATE SET enabled=EXCLUDED.enabled,limit_type=EXCLUDED.limit_type,monthly_spending_limit_cents=EXCLUDED.monthly_spending_limit_cents,confirmed_unlimited_at=EXCLUDED.confirmed_unlimited_at,updated_by_user_id=EXCLUDED.updated_by_user_id,updated_at=now() RETURNING *",[s.tenantId,b.enabled,b.limitType,b.enabled&&b.limitType==="FIXED"?b.monthlySpendingLimitCents:null,s.userId]);await c.query("INSERT INTO subscription_events(tenant_id,subscription_id,event_type,actor_user_id,metadata) SELECT $1,id,'USAGE_CREDIT_UPDATED',$2,$3 FROM tenant_subscriptions WHERE tenant_id=$1",[s.tenantId,s.userId,{before,after:x.rows[0]}]);await audit(c,s.userId,"billing.usage_credit.update","usage_credit",s.tenantId,before,x.rows[0],s.tenantId);return {setting:x.rows[0]}})});
 app.post("/root/billing/tenants/:tenantId/contract",async r=>{const root=await requireRoot(r);const b=z.object({planId:uuid,billingCycle:cycles}).parse(r.body);const tenantId=uuid.parse((r.params as Record<string, string>).tenantId);const subscription=await contractPlanForTenant(tenantId,b.planId,b.billingCycle,root.userId);await audit(db,root.userId,"billing.contract.create","subscription",subscription.id,null,subscription,tenantId);return {subscription};});
 /**
  * Conta de cobranca do tenant (§ pagador). O ROOT e a autoridade: e ele quem
  * contrata plano e concede bonus, entao e ele quem registra o pagador.
  *
  * Sem esta conta, charges.ts:47 envia o pagamento ao gateway sem document/email
  * e reconciler.ts:60 nao consegue fixar o provider preferencial da fatura,
  * caindo no primeiro provedor conectado. A tabela existia desde 0132 e nunca
  * teve produtor.
  */
 app.get("/root/billing/tenants/:tenantId/account",async r=>{await requireRoot(r);const tenantId=uuid.parse((r.params as Record<string, string>).tenantId);const x=await db.query("SELECT id,tenant_id,provider_id,external_customer_id,document,email,created_at,updated_at FROM billing_accounts WHERE tenant_id=$1",[tenantId]);return {account:x.rows[0]??null};});
 app.put("/root/billing/tenants/:tenantId/account",async r=>{const root=await requireRoot(r);const tenantId=uuid.parse((r.params as Record<string, string>).tenantId);const b=z.object({providerCode:z.string().trim().min(1),environment:providerEnvironment.default("production"),document:z.string().trim().min(1).max(32).nullable().optional(),email:z.string().trim().email().max(320).nullable().optional(),externalCustomerId:z.string().trim().max(200).nullable().optional()}).strict().parse(r.body);
  return tx(async c=>{
   const tenant=(await c.query("SELECT id FROM tenants WHERE id=$1",[tenantId])).rows[0];
   if(!tenant)throw Object.assign(new Error("Workspace não encontrado"),{statusCode:404});
   // Existência primeiro, homologação depois: um código inexistente é 404, não
   // "não homologado". E a homologação vem da COLUNA da linha carregada, não de
   // uma lista no código — promover um gateway novo é um UPDATE.
   const provider=(await c.query<{id:string;homologated:boolean}>("SELECT id,homologated FROM billing_providers WHERE code=$1 AND environment=$2",[b.providerCode,b.environment])).rows[0];
   if(!provider)throw Object.assign(new Error("Provedor de cobrança não encontrado"),{statusCode:404,code:"BILLING_PROVIDER_NOT_FOUND"});
   if(provider.homologated!==true)throw providerNotHomologated(b.providerCode);
   const before=(await c.query("SELECT * FROM billing_accounts WHERE tenant_id=$1",[tenantId])).rows[0]??null;
   const x=await c.query(`INSERT INTO billing_accounts(tenant_id,provider_id,external_customer_id,document,email)
     VALUES($1,$2,$3,$4,$5)
     ON CONFLICT(tenant_id) DO UPDATE SET provider_id=EXCLUDED.provider_id,external_customer_id=EXCLUDED.external_customer_id,document=EXCLUDED.document,email=EXCLUDED.email,updated_at=now()
     RETURNING id,tenant_id,provider_id,external_customer_id,document,email,created_at,updated_at`,
    [tenantId,provider.id,b.externalCustomerId??null,b.document??null,b.email??null]);
   await audit(c,root.userId,"billing.account.upsert","billing_account",x.rows[0].id,before,x.rows[0],tenantId);
   return {account:x.rows[0]};
  });
 });
 /** Faturas para a aba Cobrancas do painel ROOT, que ate entao nao tinha endpoint de consulta. */
 app.get("/root/billing/reconciliation-findings",async r=>{await requireRoot(r);const q=z.object({tenantId:uuid.optional(),resolved:z.enum(["true","false"]).transform(v=>v==="true").optional(),page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(100).default(25)}).parse(r.query);const x=await db.query(`SELECT * FROM mercadopago_reconciliation_findings WHERE ($1::uuid IS NULL OR tenant_id=$1) AND ($2::boolean IS NULL OR (resolved_at IS NOT NULL)=$2) ORDER BY detected_at DESC,id DESC LIMIT $3 OFFSET $4`,[q.tenantId??null,q.resolved??null,q.limit,(q.page-1)*q.limit]);return {findings:x.rows,page:q.page,limit:q.limit};});
 app.get("/root/billing/invoices",async r=>{await requireRoot(r);const q=z.object({tenantId:uuid.optional(),status:z.string().trim().max(40).optional(),limit:z.coerce.number().int().min(1).max(200).default(50)}).parse(r.query);
  const x=await db.query(`SELECT i.id,i.tenant_id,t.name tenant_name,i.subscription_id,i.provider_id,i.external_id,i.kind,i.amount_cents,i.currency,i.status,i.due_date,i.period_start,i.period_end,i.paid_at,i.created_at,
    COALESCE((SELECT json_agg(json_build_object('id',p.id,'status',p.status,'amount_cents',p.amount_cents,'method',p.method,'paid_at',p.paid_at) ORDER BY p.created_at DESC) FROM payments p WHERE p.invoice_id=i.id),'[]'::json) payments
    FROM invoices i JOIN tenants t ON t.id=i.tenant_id
    WHERE ($1::uuid IS NULL OR i.tenant_id=$1) AND ($2::text IS NULL OR i.status=$2)
    ORDER BY i.created_at DESC LIMIT $3`,[q.tenantId??null,q.status??null,q.limit]);
  return {invoices:x.rows};});
 app.post("/root/billing/tenants/:tenantId/bonus",async r=>{const root=await requireRoot(r);const b=z.object({amount:z.number().int().positive(),reason:z.string().trim().min(1).max(500),expiresAt:z.string().datetime().nullable().optional()}).parse(r.body);const tenantId=uuid.parse((r.params as Record<string, string>).tenantId);return tx(async c=>{const sub=(await c.query("SELECT id FROM tenant_subscriptions WHERE tenant_id=$1 FOR UPDATE",[tenantId])).rows[0];if(!sub)throw Object.assign(new Error("Assinatura não encontrada"),{statusCode:404});const period=(await c.query<{id:string;usage_unit:string}>("SELECT id,usage_unit FROM usage_periods WHERE tenant_id=$1 AND status='OPEN' ORDER BY sequence DESC LIMIT 1 FOR UPDATE",[tenantId])).rows[0];if(!period)throw Object.assign(new Error("Período aberto não encontrado"),{statusCode:409});// A grant precisa da MESMA usage_unit do período travado (consumo casa por unidade); o default INTERACTION deixaria bônus em período CREDIT inutilizável.
const g=(await c.query("INSERT INTO usage_grants(tenant_id,usage_period_id,usage_unit,amount,reason,granted_by_user_id,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *",[tenantId,period.id,period.usage_unit,b.amount,b.reason,root.userId,b.expiresAt??null])).rows[0];await c.query("UPDATE usage_periods SET bonus_granted=bonus_granted+$2,updated_at=now() WHERE id=$1",[period.id,b.amount]);await c.query("INSERT INTO subscription_events(tenant_id,subscription_id,event_type,actor_user_id,metadata) VALUES($1,$2,'BONUS_GRANTED',$3,$4)",[tenantId,sub.id,root.userId,{grant:g}]);await audit(c,root.userId,"billing.bonus.grant","usage_grant",g.id,null,g,tenantId);return {grant:g};});});
 app.get("/root/billing/pricing/rule",async r=>{await requireRoot(r);return {rule:(await db.query("SELECT * FROM ai_pricing_rules WHERE active=true LIMIT 1")).rows[0]??null};});
 app.get("/root/billing/pricing/models",async r=>{await requireRoot(r);return {prices:(await db.query("SELECT * FROM ai_model_prices WHERE effective_from<=now() AND (effective_to IS NULL OR effective_to>now()) ORDER BY model")).rows};});
 app.post("/root/billing/pricing/models",async r=>{const root=await requireRoot(r);const b=z.object({model:z.string().trim().min(1),inputPricePerMillionMicros:z.number().int().nonnegative(),outputPricePerMillionMicros:z.number().int().nonnegative(),cachedInputPricePerMillionMicros:z.number().int().nonnegative().nullable().optional(),effectiveFrom:z.string().datetime().optional(),effectiveTo:z.string().datetime().nullable().optional()}).parse(r.body);return tx(async c=>{const x=(await c.query("INSERT INTO ai_model_prices(model,input_price_per_million_micros,output_price_per_million_micros,cached_input_price_per_million_micros,effective_from,effective_to) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",[b.model,b.inputPricePerMillionMicros,b.outputPricePerMillionMicros,b.cachedInputPricePerMillionMicros??null,b.effectiveFrom??new Date().toISOString(),b.effectiveTo??null])).rows[0];await audit(c,root.userId,"billing.model_price.create","ai_model_price",x.id,null,x);return {price:x};});});
 app.post("/root/billing/pricing/rule",async r=>{const root=await requireRoot(r);const b=z.object({strategy:z.enum(["COST_PLUS_MARKUP","FIXED_PER_INTERACTION","CUSTOM"]),markupBps:z.number().int().min(0).optional(),fixedPricePerInteractionCents:z.number().int().nonnegative().optional(),config:z.record(z.unknown()).default({})}).parse(r.body);if(b.strategy==="COST_PLUS_MARKUP"&&b.markupBps==null||b.strategy==="FIXED_PER_INTERACTION"&&b.fixedPricePerInteractionCents==null)throw Object.assign(new Error("Regra incompleta"),{statusCode:400});return tx(async c=>{await c.query("UPDATE ai_pricing_rules SET active=false WHERE active=true");const x=(await c.query("INSERT INTO ai_pricing_rules(version,strategy,markup_bps,fixed_price_per_interaction_cents,config,active,created_by_user_id) SELECT COALESCE(max(version),0)+1,$1,$2,$3,$4,true,$5 FROM ai_pricing_rules RETURNING *",[b.strategy,b.markupBps??null,b.fixedPricePerInteractionCents??null,b.config,root.userId])).rows[0];invalidatePricingRuleCache();await audit(c,root.userId,"billing.pricing_rule.create","ai_pricing_rule",x.id,null,x);return {rule:x};});});
 app.patch("/root/billing/settings",async r=>{const root=await requireRoot(r);
  // Tipos/faixas explícitos por coluna: antes era z.record(z.unknown()) e um
  // valor com tipo errado (string em coluna int etc.) estourava 500 no Postgres.
  const bps=z.number().int().min(0).max(10_000);
  const cents=z.number().int().min(0).max(Number.MAX_SAFE_INTEGER);
  const b=z.object({
    default_rollover_rate_bps:bps.optional(),
    default_rollover_max_percentage_bps:bps.optional(),
    default_rollover_expiration_periods:z.number().int().min(1).max(120).optional(),
    usd_brl_rate_micros:z.number().int().min(1).max(Number.MAX_SAFE_INTEGER).optional(),
    credit_min_cents:cents.optional(),
    credit_max_cents:cents.optional(),
    credit_suggested_cents:z.array(cents).max(20).optional(),
    allow_custom_credit:z.boolean().optional(),
    allow_unlimited_credit:z.boolean().optional(),
    quota_alert_thresholds_bps:z.array(bps).max(10).optional(),
    credit_alert_thresholds_bps:z.array(bps).max(10).optional(),
    min_overage_estimate_cents:cents.optional(),
    reservation_ttl_minutes:z.number().int().min(1).max(1440).optional(),
    webhook_tolerance_seconds:z.number().int().min(1).max(86_400).optional()
  }).strict().parse(r.body);
  const keys=Object.keys(b);
  return tx(async c=>{const before=await getBillingSettings(c);if(b.credit_min_cents!=null&&b.credit_max_cents!=null&&b.credit_min_cents>b.credit_max_cents)throw Object.assign(new Error("Faixa inválida"),{statusCode:400});const set=keys.map((k,i)=>`${k}=$${i+2}`).join(",");const x=await c.query(`UPDATE billing_settings SET ${set},updated_at=now() WHERE id=$1::boolean RETURNING *`,[true,...keys.map(k=>(b as Record<string, unknown>)[k])]);invalidateBillingSettingsCache();await audit(c,root.userId,"billing.settings.update","billing_settings","true",before,x.rows[0]);return {settings:x.rows[0]}})});
 app.get("/root/billing/metrics",async r=>{await requireRoot(r);const q=z.object({tenantId:uuid.optional(),planId:uuid.optional(),start:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),end:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional()}).parse(r.query);return {metrics:await getRootBillingMetrics(q)}});
 // Administrative read/write surfaces. ROOT only; tenantId is explicit for all tenant data.
 app.get("/root/billing/dunning",async r=>{await requireRoot(r);const q=z.object({tenantId:uuid.optional(),page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(100).default(25)}).parse(r.query);const x=await db.query(`SELECT a.*,i.status invoice_status,i.amount_cents,i.due_date FROM billing_dunning_attempts a JOIN invoices i ON i.id=a.invoice_id WHERE ($1::uuid IS NULL OR a.tenant_id=$1) ORDER BY a.created_at DESC,a.id DESC LIMIT $2 OFFSET $3`,[q.tenantId??null,q.limit,(q.page-1)*q.limit]);return {attempts:x.rows,page:q.page,limit:q.limit}});
 app.get("/root/billing/ledger",async r=>{await requireRoot(r);const q=z.object({tenantId:uuid,page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(100).default(25)}).parse(r.query);const x=await db.query("SELECT * FROM financial_ledger WHERE tenant_id=$1 ORDER BY created_at DESC,id DESC LIMIT $2 OFFSET $3",[q.tenantId,q.limit,(q.page-1)*q.limit]);return {entries:x.rows,page:q.page,limit:q.limit}});
 app.get("/root/billing/fraud-signals",async r=>{await requireRoot(r);const q=z.object({tenantId:uuid,page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(100).default(25)}).parse(r.query);const x=await db.query("SELECT * FROM fraud_signals WHERE tenant_id=$1 ORDER BY created_at DESC,id DESC LIMIT $2 OFFSET $3",[q.tenantId,q.limit,(q.page-1)*q.limit]);return {signals:x.rows,page:q.page,limit:q.limit}});
 app.get("/root/billing/coupons",async r=>{await requireRoot(r);const q=z.object({page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(100).default(25)}).parse(r.query);const x=await db.query("SELECT id,code,discount_type,discount_value,starts_at,expires_at,max_redemptions,redemption_count,eligibility,active,created_at,updated_at FROM promotional_coupons ORDER BY created_at DESC,id DESC LIMIT $1 OFFSET $2",[q.limit,(q.page-1)*q.limit]);return {coupons:x.rows,page:q.page,limit:q.limit}});
 app.post("/root/billing/coupons",async r=>{const root=await requireRoot(r);const b=z.object({code:z.string().trim().min(1).max(64),discountType:z.enum(["PERCENT","FIXED"]),discountValue:z.number().int().nonnegative(),startsAt:z.string().datetime().optional(),expiresAt:z.string().datetime().nullable().optional(),maxRedemptions:z.number().int().positive().nullable().optional(),eligibility:z.record(z.unknown()).default({})}).strict().parse(r.body);return tx(async c=>{const x=(await c.query("INSERT INTO promotional_coupons(code,discount_type,discount_value,starts_at,expires_at,max_redemptions,eligibility) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,code,discount_type,discount_value,starts_at,expires_at,max_redemptions,redemption_count,eligibility,active,created_at,updated_at",[b.code.toUpperCase(),b.discountType,b.discountValue,b.startsAt??new Date().toISOString(),b.expiresAt??null,b.maxRedemptions??null,b.eligibility])).rows[0];await audit(c,root.userId,"billing.coupon.create","coupon",x.id,null,x);return {coupon:x}})});
 app.patch("/root/billing/coupons/:id",async r=>{const root=await requireRoot(r);const id=uuid.parse((r.params as {id:string}).id);const b=z.object({active:z.boolean()}).strict().parse(r.body);return tx(async c=>{const before=(await c.query("SELECT id,active FROM promotional_coupons WHERE id=$1",[id])).rows[0];if(!before)throw Object.assign(new Error("Cupom não encontrado"),{statusCode:404});const x=(await c.query("UPDATE promotional_coupons SET active=$2,updated_at=now() WHERE id=$1 RETURNING id,code,active,updated_at",[id,b.active])).rows[0];await audit(c,root.userId,"billing.coupon.toggle","coupon",id,before,x);return {coupon:x}})});
 app.get("/root/billing/plans/:id/prices",async r=>{await requireRoot(r);return {prices:await listPlanPrices(uuid.parse((r.params as Record<string, string>).id))}});
 app.put("/root/billing/plans/:id/prices/:cycle",async r=>{const root=await requireRoot(r);const b=z.object({basePriceCents:z.number().int().nonnegative(),discountType:z.enum(["PERCENT","FIXED"]).nullable().optional(),discountValue:z.number().int().nonnegative().nullable().optional(),currency:z.string().regex(/^[A-Z]{3}$/)}).parse(r.body);return tx(async c=>{const p=await upsertPlanPrice(c,{planId:uuid.parse((r.params as Record<string, string>).id),billingCycle:cycles.parse((r.params as Record<string, string>).cycle),...b},root.userId);await audit(c,root.userId,"billing.plan_price.update","plan_price",p.id,null,p);return {price:p}})});
 app.get("/root/billing/providers",async r=>{await requireRoot(r);return {providers:await listProviders()}});
 app.post("/root/billing/providers/:environment/oauth/begin",async r=>{const root=await requireRoot(r);const env=providerEnvironment.parse((r.params as Record<string, string>).environment);const b=z.object({redirectUri:z.string().url()}).strict().parse(r.body);try{return await beginMercadoPagoOAuth(mercadopagoCode,env,root.userId,b.redirectUri,dependencies.fetchImpl)}catch(error){throw safeError(error)}});
 app.get("/billing/providers/mercadopago/oauth/callback",async (r,reply)=>{const q=z.object({state:z.string().min(1),code:z.string().min(1)}).parse(r.query);try{await completeMercadoPagoOAuth(q.state,q.code,dependencies.fetchImpl);return reply.redirect("/root/saas/gateways?mercadopago=connected")}catch{ return reply.redirect("/root/saas/gateways?mercadopago=error") }});
 app.post("/root/billing/providers/:environment/oauth/refresh",async r=>{await requireRoot(r);const env=providerEnvironment.parse((r.params as {environment: unknown}).environment);try{return {provider:await refreshMercadoPagoToken(mercadopagoCode,env,dependencies.fetchImpl)}}catch(error){throw safeError(error)}});
 app.post("/root/billing/providers/:environment/test-connection",async r=>{await requireRoot(r);const env=providerEnvironment.parse((r.params as {environment: unknown}).environment);try{return {connection:await testMercadoPagoConnection(mercadopagoCode,env,dependencies.fetchImpl)}}catch(error){throw safeError(error)}});
 app.put("/root/billing/providers/:code/:environment/credentials",async r=>{const root=await requireRoot(r);const params=r.params as {code: string; environment: string};const b=z.object({credentials:z.record(z.unknown())}).strict().parse(r.body);assertHomologatedProvider(params.code);return {provider:await saveEncryptedCredentials(params.code,providerEnvironment.parse(params.environment),b.credentials,root.userId)}});
 /**
  * Segredo de assinatura do webhook (Mercado Pago > Suas integrações > Webhooks).
  * Sem ele, handleWebhook rejeita todo evento e a fatura nunca é confirmada.
  * O valor é write-only: nunca é devolvido, só o booleano `has_webhook_secret`.
  */
 app.put("/root/billing/providers/:code/:environment/webhook-secret",async r=>{const root=await requireRoot(r);const params=r.params as {code: string; environment: string};const b=z.object({webhookSecret:z.string().trim().min(1).max(500)}).strict().parse(r.body);assertHomologatedProvider(params.code);const provider=await saveWebhookSecret(params.code,providerEnvironment.parse(params.environment),b.webhookSecret,root.userId);await audit(db,root.userId,"billing.provider.webhook_secret.rotate","billing_provider",provider.id,null,{code:params.code,environment:params.environment});return {provider}});
 app.patch("/root/billing/providers/:code/:environment/config",async r=>{await requireRoot(r);const params=r.params as {code: string; environment: string};const b=z.record(z.unknown()).parse(r.body);assertHomologatedProvider(params.code);return {provider:await updateCommercialConfig(params.code,providerEnvironment.parse(params.environment),b)}});
 app.post("/root/billing/providers/:code/:environment/enabled",async r=>{const root=await requireRoot(r);const params=r.params as {code: string; environment: string};const b=z.object({enabled:z.boolean()}).strict().parse(r.body);if (b.enabled) assertHomologatedProvider(params.code);try{return {provider:await setEnabled(params.code,providerEnvironment.parse(params.environment),b.enabled,root.userId)}}catch(error){throw safeError(error)}});
 app.post("/root/billing/providers/:code/:environment/disconnect",async r=>{const root=await requireRoot(r);const params=r.params as {code: string; environment: string};const b=z.object({confirm:z.literal(true)}).parse(r.body);void b;assertHomologatedProvider(params.code);const provider=await disconnect(params.code,providerEnvironment.parse(params.environment),root.userId);return {provider,remoteRevocation:"Mercado Pago não oferece API para revogação remota. Para revogar totalmente o acesso, o vendedor deve fazê-lo manualmente em sua conta do Mercado Pago, em Configurações > Suas integrações."}});
}
