"use client";

import { FormEvent, useEffect, useState } from "react";
import { Shell } from "@/components/shell";
import { api } from "@/lib/api";
import { usePermission } from "@/lib/use-permission";
import { QRCodeSVG } from "qrcode.react";
import { AdminPage, AdminPageHeader } from "@/components/admin";
import { KpiCard, KpiGrid } from "@/components/ui";


type Dashboard = { planName?: string|null; includedLimit: number|null; includedUsage: number; rolloverGranted: number; rolloverUsage: number; bonusGranted: number; bonusUsage: number; totalAvailable: number|null; totalUsed: number; usedPercentBps?: number; periodEnd?: string; daysUntilRenewal?: number; creditLimitCents?: number|null; creditUsedCents?: number; [key:string]: unknown };
type Credit = { setting?: { enabled?: boolean; limit_type?: "FIXED"|"UNLIMITED"; monthly_spending_limit_cents?: number|null }; allowed?: { suggested?: number; min?: number; max?: number; allowCustom?: boolean; allowUnlimited?: boolean } };
type Invoice = { id:string; amount_cents:string|number; currency:string; status:string; period_start?:string|null; period_end?:string|null; charge?: { invoiceId?:string; id:string; status:string; qr_code?:string|null; ticket_url?:string|null }|null; line_items?: Array<{ description?:string; amount_cents?:string|number }> };
const n = (v: unknown) => typeof v === "number" ? v.toLocaleString("pt-BR") : "—";
const money = (v: unknown) => typeof v === "number" ? (v/100).toLocaleString("pt-BR", { style:"currency", currency:"BRL" }) : "—";
const err = (e: unknown) => e instanceof Error ? e.message : "Não foi possível carregar os dados.";

export default function UsoPage() {
  const canManage = usePermission("billing.manage");
  const [dashboard,setDashboard] = useState<Dashboard|null>(); const [history,setHistory] = useState<Invoice[]>([]); const [credit,setCredit] = useState<Credit>();
  const [loading,setLoading] = useState(true); const [error,setError] = useState("");
  async function load() { setLoading(true); setError(""); try { const [d,h,c] = await Promise.all([api<{dashboard:Dashboard|null}>("/billing/usage-dashboard"), api<{history:Invoice[]}>("/billing/history?limit=20"), api<Credit>("/billing/usage-credit")]); setDashboard(d.dashboard); setHistory(h.history ?? []); setCredit(c); } catch(e) { setError(err(e)); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  return <Shell><AdminPage><AdminPageHeader title="Uso" description="Consumo de créditos de IA do tenant e histórico de cobrança." />
    {error && <div role="alert" className="mb-4 border-y border-[var(--warning-border)] bg-[var(--warning-subtle)] px-4 py-4 flex justify-between gap-3"><span>{error}</span><button className="btn warn" onClick={() => void load()}>Tentar novamente</button></div>}
    {loading ? <div role="status" aria-busy="true"><span className="sr-only">Carregando uso</span><div className="skeleton h-72" /></div> : dashboard === null ? <div className="card"><h2>Nenhum período de uso disponível</h2><p className="sub">Ainda não há dados de consumo para este tenant.</p></div> : dashboard ? <><Usage dashboard={dashboard}/><CreditForm data={credit} canManage={canManage}/><History history={history} onReload={load}/></> : null}
  </AdminPage></Shell>;
}
function Usage({dashboard:d}:{dashboard:Dashboard}) { const unlimited=d.totalAvailable==null; const pct=unlimited?0:Math.min(100, Math.max(0,(d.usedPercentBps??0)/100)); const reached=!unlimited && (d.totalUsed >= (d.totalAvailable ?? 0)); return <><KpiGrid aria-label="Resumo de uso">
 {[["Incluído",d.includedLimit==null?"Ilimitado":n(d.includedLimit),"Créditos de IA"],["Acumulado",n(d.rolloverGranted),"Franquia acumulada"],["Bônus",n(d.bonusGranted),"Créditos de IA"],["Total usado",n(d.totalUsed),"Interações acumuladas"]].map(([a,b,c])=><KpiCard key={a} label={a} value={b} hint={c}/>)}
 </KpiGrid><section className="card mt-4"><div className="flex flex-wrap justify-between gap-2"><div><h2>Interações acumuladas</h2><p className="sub">{unlimited?"Uso ilimitado":`${n(d.totalUsed)} de ${n(d.totalAvailable)} interações`}</p></div><strong>{unlimited?"—":`${pct.toLocaleString("pt-BR")} %`}</strong></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-[var(--border)]" role="progressbar" aria-label="Uso de créditos de IA" aria-valuemin={0} aria-valuemax={unlimited?undefined:100} aria-valuenow={unlimited?undefined:pct}><div className={`h-full ${reached?"bg-[var(--danger)]":pct>=80?"bg-[var(--warning)]":"bg-[var(--primary)]"}`} style={{width:unlimited?"100%":`${pct}%`}}/></div>{reached&&<p className="error mt-3" role="alert">Quota atingida. Novas interações podem depender do crédito de uso.</p>}<p className="sub mt-3">Renova em {d.daysUntilRenewal==null?"—":`${d.daysUntilRenewal} dias`} ({d.periodEnd?new Date(d.periodEnd).toLocaleDateString("pt-BR"):"—"}).</p></section><section className="grid gap-4 mt-4 sm:grid-cols-2"><div className="card"><h2>Crédito de uso</h2><strong>{money(d.creditUsedCents)}</strong><p className="sub">de {d.creditLimitCents==null?"sem limite":money(d.creditLimitCents)} · excedente em BRL</p></div><div className="card"><h2>Rollover</h2><p className="sub">A franquia acumulada nunca representa dinheiro. {typeof d.rolloverPreviewInteractions === "number"?`Estimativa: ${n(d.rolloverPreviewInteractions)} interações.`:"A prévia não está disponível."}</p></div></section></> }
function CreditForm({data,canManage}:{data?:Credit;canManage:boolean}) { const a=data?.allowed; const s=data?.setting; const [enabled,setEnabled]=useState(Boolean(s?.enabled)); const [type,setType]=useState<"FIXED"|"UNLIMITED">(s?.limit_type??"FIXED"); const [amount,setAmount]=useState(String(Number(s?.monthly_spending_limit_cents??a?.suggested??0)/100)); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 useEffect(()=>{if(s){setEnabled(Boolean(s.enabled));setType(s.limit_type??"FIXED");setAmount(s.monthly_spending_limit_cents==null?String(Number(a?.suggested??0)/100):String(s.monthly_spending_limit_cents/100));}},[s,a]);
 async function submit(e:FormEvent){e.preventDefault();if(!canManage||saving)return;if(enabled&&type==="UNLIMITED"&&!window.confirm("Crédito ilimitado permite excedentes sem teto mensal em BRL e pode gerar cobranças variáveis. Confirma?"))return;setSaving(true);setMessage("");try{await api("/billing/usage-credit",{method:"PUT",body:JSON.stringify({enabled,limitType:type,monthlySpendingLimitCents:enabled&&type==="FIXED"?Math.round(Number(amount)*100):null,confirmUnlimited:enabled&&type==="UNLIMITED"})});setMessage("Configuração salva.")}catch(e){setMessage(err(e));}finally{setSaving(false)}}
 return <section className="card mt-4"><h2>Configurações de crédito de uso</h2><p className="sub mb-4">Limite de excedente mensal em BRL. Os valores sugeridos vêm da política do tenant.</p><form onSubmit={submit} aria-busy={saving}><fieldset disabled={!canManage||saving} className="grid gap-4 sm:grid-cols-2"><label className="field"><span className="label">Crédito de uso</span><select className="input" value={enabled?"on":"off"} onChange={e=>setEnabled(e.target.value==="on")}><option value="off">Desativado</option><option value="on">Ativado</option></select></label>{enabled&&<label className="field"><span className="label">Tipo de limite</span><select className="input" value={type} onChange={e=>setType(e.target.value as "FIXED"|"UNLIMITED")}><option value="FIXED">Valor personalizado</option>{a?.allowUnlimited&&<option value="UNLIMITED">Ilimitado</option>}</select></label>}{enabled&&type==="FIXED"&&<label className="field"><span className="label">Limite mensal (BRL)</span><input className="input" type="number" min={a?.min==null?undefined:a.min/100} max={a?.max==null?undefined:a.max/100} step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/><small className="sub">Sugerido: {money(a?.suggested)} · faixa: {money(a?.min)} a {money(a?.max)}</small></label>}</fieldset>{!canManage&&<p className="sub mt-3">Acesso somente leitura.</p>}{message&&<p role="status" className="mt-3">{message}</p>}{canManage&&<button className="btn primary mt-4" disabled={saving}>{saving?"Salvando…":"Salvar crédito de uso"}</button>}</form></section> }
function statusLabel(s:string){return ({paid:"Pago",pending:"Pendente",open:"Aberta",overdue:"Em atraso",failed:"Falhou"} as Record<string,string>)[s.toLowerCase()]??s}
function History({history,onReload}:{history:Invoice[];onReload:()=>Promise<void>}) { const canManage=usePermission("billing.manage"); const [selected,setSelected]=useState<Invoice["id"]>(); const [charge,setCharge]=useState<Invoice["charge"]>(); const [message,setMessage]=useState("");
 useEffect(()=>{if(!charge||!selected||["paid","approved"].includes(charge.status.toLowerCase()))return;const timer=window.setInterval(async()=>{try{const r=await api<{charge:Invoice["charge"]}>(`/billing/invoices/${selected}/payment`);setCharge(r.charge);await onReload()}catch{ /* polling retries silently */ }},7000);return()=>window.clearInterval(timer)},[charge,selected,onReload]);
 async function pay(i:Invoice){setMessage("");try{const r=await api<{charge:NonNullable<Invoice["charge"]>}>(`/billing/invoices/${i.id}/charge`,{method:"POST",body:JSON.stringify({method:"pix"})});setSelected(i.id);setCharge(r.charge)}catch(e){setMessage(err(e))}}
 return <section className="card mt-4"><h2>Histórico mensal</h2>{message&&<p role="alert" className="error mt-2">{message}</p>}{history.length===0?<p className="sub mt-3">Nenhuma fatura encontrada.</p>:<div className="mt-3 grid gap-3">{history.map(i=><details key={i.id} open={selected===i.id} onToggle={e=>{if((e.currentTarget as HTMLDetailsElement).open){setSelected(i.id);setCharge(undefined);void (async()=>{if(canManage){const r=await api<{charge:Invoice["charge"]}>(`/billing/invoices/${i.id}/payment`);setCharge(r.charge)}})()}}} className="border-b border-[var(--border)] pb-3"><summary className="cursor-pointer flex justify-between gap-3"><span>{i.period_start?new Date(i.period_start).toLocaleDateString("pt-BR"):"Período não informado"} – {i.period_end?new Date(i.period_end).toLocaleDateString("pt-BR"):"Período não informado"} · {statusLabel(i.status)}</span><strong>{money(Number(i.amount_cents))}</strong></summary>{canManage&&['pending','open','overdue'].includes(i.status.toLowerCase())&&<button className="btn primary mt-3" onClick={()=>void pay(i)}>Pagar com PIX</button>}{charge&&selected===i.id&&<div className="mt-3 grid gap-3 sm:grid-cols-[auto_1fr] items-center"><div>{charge.qr_code?<QRCodeSVG value={charge.qr_code} size={180}/>:<p className="sub">QR indisponível</p>}</div><div><p role="status">Status: {statusLabel(charge.status)}{['paid','approved'].includes(charge.status.toLowerCase())?" — acesso restabelecido.":" — aguardando pagamento…"}</p>{charge.qr_code&&<button className="btn mt-2" onClick={()=>void navigator.clipboard.writeText(charge.qr_code!)}>Copiar PIX</button>}{charge.ticket_url&&<a className="btn mt-2 ml-2" href={charge.ticket_url} target="_blank" rel="noreferrer">Abrir link</a>}</div></div>}{i.line_items?.length?<ul className="mt-2 pl-5 text-sm">{i.line_items.map((l,j)=><li key={j}>{l.description??"Linha da fatura"}: {money(Number(l.amount_cents))}</li>)}</ul>:<p className="sub mt-2">Sem linhas de fatura.</p>}</details>)}</div>}</section> }
