const entitySelectors = {
  "/": "main > section",
  "/agenda": "main [aria-label*='agenda' i], main [data-testid*='agenda' i]",
  "/conversas": "main [aria-label='Lista de conversas'], main [aria-label^='Histórico da conversa com']",
  "/contatos": "main .leads-table tbody tr",
  "/contatos/[id]": "main [aria-labelledby='internal-notes-title'], main [aria-labelledby='qualification-title']",
  "/pipeline": "main [aria-label='Quadro de pipeline']",
  "/configuracoes": "main [aria-label*='configuração' i], main [aria-label*='configuração' i]",
  "/agenda": "main [aria-label*='agenda' i], main [data-testid*='agenda' i]"
};
const populated = (heading, marker, route) => ({ expectedPath: null, heading, marker, headingRole: "heading", entitySelector: entitySelectors[route] ?? "main > section", state: "populated" });
export const ROUTE_CONTRACTS = {
  "/": populated("Visão geral|Minha operação", "Dashboard de reuniões|Mariana Oliveira", "/"),
  "/agenda": populated("Agenda", "Reunião Cliente QA|qa-appt|Cliente QA", "/agenda"),
  "/agente": populated("Agente principal", "Agente QA|active", "/agente"),
  "/alertas": populated("Alertas operacionais", "Conexão verificada|qa-alert", "/alertas"),
  "/conexao": populated("Conexão", "qa-connection|connected|WhatsApp", "/conexao"),
  "/configuracoes": populated("Configurações", "AtendON QA|qa-cat|whatsapp", "/configuracoes"),
  "/conversas": populated("Conversas|Minhas conversas", "Marina QA|Preciso confirmar|qa-conversation", "/conversas"),
  "/follow-ups": populated("Follow-ups", "Retornar contato|qa-followup", "/follow-ups"),
  "/humanizacao": populated("Humanização", "professional|Timing", "/humanizacao"),
  "/contatos": populated("Contatos", "Cliente QA com nome comercial deliberadamente longo", "/contatos"),
  "/contatos/[id]": { expectedPath: null, heading: "Cliente QA com nome comercial deliberadamente longo", headingRole: "heading", marker: "qa-note", entitySelector: "[aria-labelledby='internal-notes-title']", state: "populated" },
  "/pipeline": populated("Pipeline", "Cliente QA com nome comercial deliberadamente longo", "/pipeline"),
  "/pos-venda": populated("Carteira de pós-venda", "Marina QA · Cliente de implantação empresarial|Confirmar treinamento de implantação", "/pos-venda"),
  "/pos-venda/cobranca": populated("Cobranças de crediário", "Cliente QA|qa-debt", "/pos-venda/cobranca"),
  "/pos-venda/configurar": populated("Configurar checklist", "Confirmar cadastro|Agendar treinamento", "/pos-venda/configurar"),
  "/tripz-ai": { expectedPath: null, heading: "Roteiro QA", headingRole: "heading", marker: "Roteiro QA|Roteiro QA pronto para revisão", entitySelector: "section[aria-label^='Conversa ']", state: "populated" },
  "/uso": populated("Uso", "Conversas|42|Profissional", "/uso"),
  "/workspace/audit": populated("Auditoria do workspace", "workspace.viewed|qa-log", "/workspace/audit"),
  "/workspace/members": populated("Membros", "Ana QA|ana@example.test", "/workspace/members"),
  "/workspace/roles": { expectedPath: null, heading: "Funções e permissões", headingRole: "heading", marker: "Administrador|Operador", entitySelector: ".admin-list-item", state: "populated" },
  "/root/audit": populated("Auditoria ROOT", "workspace.viewed|qa-log", "/root/audit"),
  "/root/saas/billing": populated("Operações de billing", "qa-invoice|Tenant ID", "/root/saas/billing"),
  "/root/saas/gateways": populated("Gateways", "Stripe Test|sandbox", "/root/saas/gateways"),
  "/root/saas/metricas": populated("Métricas SaaS", "Receita|Transações|Tenant ID", "/root/saas/metricas"),
  "/root/versions": { expectedPath: null, heading: "Versões e changelogs", headingRole: "heading", marker: "v2\\.1\\.0|qa-release|Release \\(major\\)", entitySelector: "table tbody tr", state: "populated" },
  "/changelog": { expectedPath: "/changelog", heading: "Changelog público", headingRole: "heading", marker: "Changelog público|AtendON 2\\.1\\.0", entitySelector: "main .card", state: "public" },
  "/privacidade": { expectedPath: "/privacidade", heading: "Política de privacidade", headingRole: "heading", marker: "privacidade|dados", entitySelector: "main", state: "public" },
  "/termos": { expectedPath: "/termos", heading: "Termos de uso", headingRole: "heading", marker: "termos|usuário", entitySelector: "main", state: "public" },
  "/root/saas/planos": populated("Planos e cobrança", "Profissional|qa-plan", "/root/saas/planos"),
  "/root/workspaces": populated("Workspaces", "AtendON QA Workspace|qa-workspace-0001", "/root/workspaces"),
  "/perfil": populated("Perfil", "qa@example.test|QA Operador", "/perfil"),
  "/alterar-senha": { expectedPath: "/alterar-senha", heading: "Crie uma nova senha", headingRole: "heading", marker: "nova senha", entitySelector: "main > section", state: "public" },
  "/403": { expectedPath: "/403", heading: "Você não tem permissão para abrir esta área\\.", headingRole: "heading", marker: "permissão para abrir esta área", entitySelector: ".denied-card", state: "error" },
  "/offline": { expectedPath: "/offline", heading: "Sem conexão no momento", headingRole: "heading", marker: "conexão", entitySelector: "main > section", state: "error" },
  "/login": { expectedPath: "/login", heading: "Boas-vindas", headingRole: "heading", marker: "senha|e-mail|email", entitySelector: "main > section", state: "public" },
  "/convite": { expectedPath: "/convite", heading: "Aceitar convite", headingRole: "heading", marker: "AtendON QA Workspace|guest@example.test", entitySelector: ".invitation-summary", state: "public" },
  "/invitations/[token]": { expectedPath: "/invitations/qa-token", heading: "Aceitar convite", headingRole: "heading", marker: "AtendON QA Workspace|guest@example.test|Operador", entitySelector: ".invitation-summary", state: "public" },
  "/meet/[roomId]": { expectedPath: "/meet/qa-room", heading: "Não foi possível entrar na sala|Sala de videochamada", headingRole: "heading", marker: "qa-room|Tentar novamente|Preparando sua sala", entitySelector: "main > section", state: "public" },
  "/reuniao/[code]": { expectedPath: "/reuniao/qa-code", heading: "Não foi possível entrar na sala|Sala de videochamada", headingRole: "heading", marker: "qa-code|Tentar novamente|Preparando sua sala", entitySelector: "main > section", state: "public" },
  "/agente/figurinhas": { expectedPath: "/follow-ups", heading: "Follow-ups", headingRole: "heading", marker: "Atraso|mídias|120", entitySelector: ".channels-ai-page, form, input", state: "populated" }
};
export function contractFor(route) { return ROUTE_CONTRACTS[route]; }
