"use client";
import React from "react";
import useSWR from "swr";
import { Shell } from "@/components/shell";
import { api } from "@/lib/api";
import type { PanelSession } from "@/lib/session";
import { AdminPage, AdminPageHeader } from "@/components/admin";
import styles from "@/components/admin/admin.module.css";
import { SaveButton, SaveToast, useSaveFeedback } from "@/components/ui";
const fetcher=<T,>(u:string)=>api<T>(u);
type Tab="dunning"|"coupons"|"ledger"|"fraud"|"reconciliation";
export default function BillingAdminPage(){
 const {data:session}=useSWR<PanelSession>("/me",fetcher); const root=Boolean(session?.user.isRoot); const [tab,setTab]=React.useState<Tab>("dunning"); const [tenantId,setTenantId]=React.useState(""); const [page,setPage]=React.useState(1);
 const endpoint=tab==="fraud"?"fraud-signals":tab; const query=tenantId?`&tenantId=${encodeURIComponent(tenantId)}`:"";
 const {data,error,mutate}=useSWR<Record<string,unknown>>(root?`/root/billing/${endpoint}?page=${page}&limit=25${query}`:null,fetcher);
 const [coupon,setCoupon]=React.useState({code:"",discountType:"PERCENT",discountValue:""}); const [message,setMessage]=React.useState(""); const couponSave=useSaveFeedback();
 async function createCoupon(e:React.FormEvent){e.preventDefault();try{await couponSave.run(async()=>{await api("/root/billing/coupons",{method:"POST",body:JSON.stringify({...coupon,discountValue:Number(coupon.discountValue)})});setCoupon({code:"",discountType:"PERCENT",discountValue:""});setMessage("Cupom criado");mutate()})}catch{setMessage("Não foi possível criar o cupom")}}
 if(!root)return <Shell><div className="card">Esta área está disponível apenas para usuários ROOT.</div></Shell>;
 const rows=(data?.[tab==="dunning"?"attempts":tab==="coupons"?"coupons":tab==="ledger"?"entries":tab==="reconciliation"?"findings":"signals"] as Record<string,unknown>[]|undefined)??[];
 return <Shell><AdminPage><AdminPageHeader title="Operações de billing" /><section className="card"><label className="field"><span className="label">Tenant ID (obrigatório para ledger e antifraude)</span><input className="input" value={tenantId} onChange={e=>{setTenantId(e.target.value);setPage(1)}} placeholder="UUID do tenant" /></label><div className={styles.actions}>{(["dunning","coupons","ledger","fraud","reconciliation"] as Tab[]).map(t=><button className="btn" type="button" key={t} onClick={()=>{setTab(t);setPage(1)}} aria-pressed={tab===t}>{t}</button>)}</div></section>{tab==="coupons"&&<form className={`card ${styles.formGrid}`} onSubmit={createCoupon}><input className="input" required placeholder="Código" value={coupon.code} onChange={e=>setCoupon({...coupon,code:e.target.value})}/><select className="input" value={coupon.discountType} onChange={e=>setCoupon({...coupon,discountType:e.target.value})}><option>PERCENT</option><option>FIXED</option></select><input className="input" required type="number" min="0" placeholder="Valor" value={coupon.discountValue} onChange={e=>setCoupon({...coupon,discountValue:e.target.value})}/><SaveButton state={couponSave.state} type="submit">Criar cupom</SaveButton>{message&&<span>{message}</span>}</form>}<SaveToast show={couponSave.done}>Cupom criado</SaveToast>{error?<p className="error">Não foi possível carregar.</p>:<section className={`card ${styles.tableScroll}`}><table className="admin-table responsive-table"><thead><tr><th>Identificador</th><th>Status</th><th>Dados</th></tr></thead><tbody>{rows.map((r,i)=><tr key={String(r.id??i)}><td data-label="Identificador">{String(r.id??r.code??r.invoice_id??r.signal_type??"")}</td><td data-label="Status">{String(r.status ?? (r.active ? "active" : (r.severity ?? "—")))}</td><td data-label="Dados"><code className="whitespace-pre-wrap break-all">{JSON.stringify(r)}</code></td></tr>)}</tbody></table><div className={styles.actions}><button className="btn" type="button" disabled={page===1} onClick={()=>setPage(page-1)}>Anterior</button><span>Página {page}</span><button className="btn" type="button" onClick={()=>setPage(page+1)}>Próxima</button></div></section>}</AdminPage></Shell>;
}