import type { FastifyInstance, FastifyRequest } from "fastify";
import { z } from "zod";
import { db } from "../../db/client.js";
import { requireRoot, requireWorkspace } from "../../auth/session.js";
import { getEffectiveEntitlements } from "../../billing/entitlements.js";
import type { EffectiveEntitlements } from "../../billing/types.js";
type PlanBody = z.infer<typeof planFields>;
import { changePlan, changeStatus, getOverLimitReport } from "./service.js";
const uuid = z.string().uuid();
const planFields = z.object({ code: z.string().trim().min(1).max(80).optional(), name: z.string().trim().min(1).max(200).optional(), description: z.string().nullable().optional(), monthlyPriceCents: z.number().int().min(0).optional(), setupPriceCents: z.number().int().min(0).optional(), currency: z.string().length(3).optional(), billingPeriodMonths: z.number().int().positive().optional(), trialDays: z.number().int().min(0).optional(), gracePeriodDays: z.number().int().min(0).optional(), isInternal: z.boolean().optional(), position: z.number().int().optional(), features: z.record(z.boolean()).optional(), limits: z.record(z.number().int().positive().nullable()).optional() });
const createPlan = planFields.required({ code: true, name: true, monthlyPriceCents: true });
async function rootAudit(request: FastifyRequest, root: { userId: string }, action: string, type: string, id: string | null, before: unknown, after: unknown, tenant: string | null = null) { await db.query(`INSERT INTO audit_logs(actor_user_id,workspace_id,actor_scope,action,resource_type,resource_id,metadata,ip_address,user_agent) VALUES($1,$2,'root',$3,$4,$5,$6,$7,$8)`, [root.userId, tenant, action, type, id, { before, after }, request.ip, request.headers["user-agent"] ?? null]); return root; }
async function planDetails(id: string) { const p = await db.query("SELECT * FROM plans WHERE id=$1", [id]); if (!p.rows[0]) throw Object.assign(new Error("Plano não encontrado"), { statusCode: 404 }); const [f, l] = await Promise.all([db.query("SELECT * FROM plan_features WHERE plan_id=$1", [id]), db.query("SELECT * FROM plan_limits WHERE plan_id=$1", [id])]); return { ...p.rows[0], features: f.rows, limits: l.rows }; }
async function usage(tenantId: string, e: EffectiveEntitlements) { const [u, w, a] = await Promise.all([db.query("SELECT count(*)::int used FROM workspace_members WHERE workspace_id=$1 AND status='active'", [tenantId]), db.query("SELECT count(*)::int used FROM whatsapp_sessions WHERE tenant_id=$1", [tenantId]), e.periodStart ? db.query("SELECT COALESCE(used,0)::int used FROM usage_counters WHERE tenant_id=$1 AND metric_key='MAX_AI_INTERACTIONS' AND period_start=$2", [tenantId, e.periodStart]) : Promise.resolve({ rows: [] as never[] })]); return { MAX_USERS: u.rows[0].used, MAX_WHATSAPP_CONNECTIONS: w.rows[0].used, MAX_AI_INTERACTIONS: a.rows[0]?.used ?? 0 }; }
export async function registerSaasRoutes(app: FastifyInstance) {
  app.get("/root/saas/plans", async (r) => { await requireRoot(r); const rows = await db.query("SELECT * FROM plans ORDER BY position,code"); return { plans: await Promise.all(rows.rows.map((p) => planDetails(p.id))) }; });
  app.post("/root/saas/plans", async (r, reply) => { const root = await requireRoot(r); const b = createPlan.parse(r.body); const x = await db.query(`INSERT INTO plans(code,name,description,monthly_price_cents,setup_price_cents,currency,billing_period_months,trial_days,grace_period_days,is_internal,position) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`, [b.code, b.name, b.description ?? null, b.monthlyPriceCents, b.setupPriceCents ?? 0, b.currency ?? "BRL", b.billingPeriodMonths ?? 1, b.trialDays ?? 0, b.gracePeriodDays ?? 7, b.isInternal ?? false, b.position ?? 0]); await rootAudit(r, root, "saas.plan.create", "plan", x.rows[0].id, null, x.rows[0]); return reply.status(201).send({ plan: await planDetails(x.rows[0].id) }); });
  app.get("/root/saas/plans/:id", async (r) => { await requireRoot(r); return { plan: await planDetails(uuid.parse((r.params as { id: string }).id)) }; });
  app.patch("/root/saas/plans/:id", async (r) => { const root = await requireRoot(r); const planId = uuid.parse((r.params as { id: string }).id); const b = planFields.parse(r.body); const before = await planDetails(planId); const map: Record<string, string> = { code: "code", name: "name", description: "description", monthlyPriceCents: "monthly_price_cents", setupPriceCents: "setup_price_cents", currency: "currency", billingPeriodMonths: "billing_period_months", trialDays: "trial_days", gracePeriodDays: "grace_period_days", isInternal: "is_internal", position: "position" }; const keys = Object.keys(b).filter((k) => k in map); if (keys.length) { const set = keys.map((k, i) => `${map[k]}=$${i + 2}`).join(","); await db.query(`UPDATE plans SET ${set},updated_at=now() WHERE id=$1`, [planId, ...keys.map((k) => (b as PlanBody)[k as keyof PlanBody])]); } for (const [key, enabled] of Object.entries(b.features ?? {})) await db.query("INSERT INTO plan_features(plan_id,feature_key,enabled) VALUES($1,$2,$3) ON CONFLICT(plan_id,feature_key) DO UPDATE SET enabled=EXCLUDED.enabled", [planId, key, enabled]); for (const [key, value] of Object.entries(b.limits ?? {})) await db.query("INSERT INTO plan_limits(plan_id,limit_key,limit_value) VALUES($1,$2,$3) ON CONFLICT(plan_id,limit_key) DO UPDATE SET limit_value=EXCLUDED.limit_value", [planId, key, value]); const after = await planDetails(planId); await rootAudit(r, root, "saas.plan.update", "plan", planId, before, after); return { plan: after }; });
  app.post("/root/saas/plans/:id/archive", async (r) => { const root = await requireRoot(r); const id = uuid.parse((r.params as { id: string }).id); const before = await planDetails(id); const x = await db.query("UPDATE plans SET status='archived',updated_at=now() WHERE id=$1 RETURNING *", [id]); await rootAudit(r, root, "saas.plan.archive", "plan", id, before, x.rows[0]); return { plan: x.rows[0] }; });
  app.post("/root/saas/plans/:id/duplicate", async (r, reply) => { const root = await requireRoot(r); const source = await planDetails(uuid.parse((r.params as { id: string }).id)); const b = z.object({ code: z.string().min(1), name: z.string().min(1).optional() }).parse(r.body ?? {}); const x = await db.query("INSERT INTO plans(code,name,description,status,monthly_price_cents,setup_price_cents,currency,billing_period_months,trial_days,grace_period_days,is_internal,position) SELECT $2,COALESCE($3,name),description,'active',monthly_price_cents,setup_price_cents,currency,billing_period_months,trial_days,grace_period_days,is_internal,position FROM plans WHERE id=$1 RETURNING *", [source.id, b.code, b.name ?? null]); for (const f of source.features) await db.query("INSERT INTO plan_features VALUES($1,$2,$3)", [x.rows[0].id, f.feature_key, f.enabled]); for (const l of source.limits) await db.query("INSERT INTO plan_limits VALUES($1,$2,$3)", [x.rows[0].id, l.limit_key, l.limit_value]); await rootAudit(r, root, "saas.plan.duplicate", "plan", x.rows[0].id, source, x.rows[0]); return reply.status(201).send({ plan: await planDetails(x.rows[0].id), actor: root.userId }); });
  app.get("/root/saas/catalog", async (r) => { await requireRoot(r); const [features, limits] = await Promise.all([db.query("SELECT * FROM feature_catalog ORDER BY feature_key"), db.query("SELECT * FROM limit_catalog ORDER BY limit_key")]); return { feature_catalog: features.rows, limit_catalog: limits.rows }; });
  app.get("/root/saas/tenants", async (r) => { await requireRoot(r); const rows = await db.query("SELECT t.id,t.name,t.status,s.status subscription_status,p.code plan_code,p.name plan_name FROM tenants t LEFT JOIN tenant_subscriptions s ON s.tenant_id=t.id LEFT JOIN plans p ON p.id=s.plan_id ORDER BY t.name"); return { tenants: await Promise.all(rows.rows.map(async (t) => ({ ...t, entitlements: await getEffectiveEntitlements(t.id), usage: await usage(t.id, await getEffectiveEntitlements(t.id)) }))) }; });
  app.get("/root/saas/tenants/:tenantId", async (r) => { await requireRoot(r); const tenantId = uuid.parse((r.params as { tenantId: string }).tenantId); const e = await getEffectiveEntitlements(tenantId); return { tenantId, entitlements: e, usage: await usage(tenantId, e), overLimit: await getOverLimitReport(tenantId) }; });
  app.post("/root/saas/tenants/:tenantId/subscription", async (r) => { const root = await requireRoot(r); const b = z.object({ planId: uuid }).parse(r.body); return { subscription: await changePlan(uuid.parse((r.params as { tenantId: string }).tenantId), b.planId, root.userId) }; });
  for (const [path, status] of [["suspend", "SUSPENDED"], ["reactivate", "ACTIVE"], ["cancel", "CANCELED"]] as const) app.post(`/root/saas/tenants/:tenantId/subscription/${path}`, async (r) => { const root = await requireRoot(r); return { subscription: await changeStatus(uuid.parse((r.params as { tenantId: string }).tenantId), status, root.userId) }; });
  app.put("/root/saas/tenants/:tenantId/overrides/:kind/:key", async (r) => { const root = await requireRoot(r); const tenantId = uuid.parse((r.params as { tenantId: string }).tenantId); const kind = z.enum(["feature", "limit"]).parse((r.params as { kind: string }).kind); const key = z.string().min(1).parse((r.params as { key: string }).key); const b = z.object({ boolValue: z.boolean().optional(), intValue: z.number().int().positive().nullable().optional(), unlimited: z.boolean().optional(), reason: z.string().max(500).optional(), expiresAt: z.string().datetime().nullable().optional() }).parse(r.body);
    // A chave precisa existir no catálogo: um typo gravaria um override silenciosamente
    // inerte, dando ao ROOT a falsa impressão de ter concedido algo.
    const catalogTable = kind === "feature" ? "feature_catalog" : "limit_catalog";
    const catalogColumn = kind === "feature" ? "feature_key" : "limit_key";
    const known = await db.query(`SELECT 1 FROM ${catalogTable} WHERE ${catalogColumn}=$1`, [key]);
    if (!known.rowCount) throw Object.assign(new Error(`Chave desconhecida para ${kind}: ${key}`), { statusCode: 400, code: "UNKNOWN_ENTITLEMENT_KEY" });
    // "ilimitado" precisa ser explícito. Sem isso, omitir intValue por engano
    // desligaria a cobrança daquele limite sem ninguém perceber.
    if (kind === "limit" && b.intValue == null && b.unlimited !== true) {
      throw Object.assign(new Error("Informe intValue ou marque unlimited para conceder limite ilimitado."), { statusCode: 400, code: "LIMIT_OVERRIDE_REQUIRES_VALUE" });
    }
    const x = await db.query("INSERT INTO tenant_entitlement_overrides(tenant_id,kind,entitlement_key,bool_value,int_value,reason,expires_at,granted_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(tenant_id,kind,entitlement_key) DO UPDATE SET bool_value=EXCLUDED.bool_value,int_value=EXCLUDED.int_value,reason=EXCLUDED.reason,expires_at=EXCLUDED.expires_at,granted_by_user_id=EXCLUDED.granted_by_user_id,updated_at=now() RETURNING *", [tenantId, kind, key, b.boolValue ?? null, b.intValue ?? null, b.reason ?? null, b.expiresAt ?? null, root.userId]); await rootAudit(r, root, "saas.override.grant", "entitlement_override", x.rows[0].id, null, x.rows[0], tenantId); return { override: x.rows[0] }; });
  app.delete("/root/saas/tenants/:tenantId/overrides/:kind/:key", async (r) => { const root = await requireRoot(r); const tenantId = uuid.parse((r.params as { tenantId: string }).tenantId); const x = await db.query("DELETE FROM tenant_entitlement_overrides WHERE tenant_id=$1 AND kind=$2 AND entitlement_key=$3 RETURNING *", [tenantId, (r.params as { kind: string }).kind, (r.params as { key: string }).key]); if (!x.rows[0]) throw Object.assign(new Error("Override não encontrada"), { statusCode: 404 }); await rootAudit(r, root, "saas.override.remove", "entitlement_override", x.rows[0].id, x.rows[0], null, tenantId); return { deleted: true }; });
  app.get("/root/saas/events", async (r) => { await requireRoot(r); return { events: (await db.query("SELECT * FROM subscription_events ORDER BY created_at DESC LIMIT 500")).rows }; });
  app.get("/billing/my-plan", async (r) => { const session = await requireWorkspace(r); const e = await getEffectiveEntitlements(session.tenantId); return { tenantId: session.tenantId, plan: { code: e.planCode, name: e.planName }, status: e.status, features: e.features, limits: e.limits, usage: await usage(session.tenantId, e) }; });
}
